Select from counties when creating broadcasts
alphagov/notifications-admin pull request #3614
Opened 2020-09-08 07:44 UTC by leohemsted

Took a little longer than expected, with a lot of rebases along the way! Did a fair bit of refactoring along the way, so it's best reviewed commit by commit, and I really do mean that.

You can now create broadcasts with rural counties, as well as metropolitan boroughs (which were already included as they're unitary districts), rural districts (local authorities), and electoral wards.

I implemented this mock-up from chris:

![image](https://www.pivotaltracker.com/file_attachments/105881790/download?inline=true&size=big)

| Rural Counties are visible                                            | ![image](https://user-images.githubusercontent.com/5020841/92446176-54a5a700-f1ad-11ea-84cf-86caa9da350e.png) |
|-----------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|
| Local Authorities are visible                                         | ![image](https://user-images.githubusercontent.com/5020841/92446149-4b1c3f00-f1ad-11ea-8776-5fa03343d3be.png) |
| Electoral Wards are NOT visible                                       | ![image](https://user-images.githubusercontent.com/5020841/92446281-8159be80-f1ad-11ea-9239-0b3f35918938.png) |
|                                                                       |                                                                                                               |
| Ward selection for a local authority is unchanged                     | ![image](https://user-images.githubusercontent.com/5020841/92446318-90d90780-f1ad-11ea-9990-95dffdda9ae6.png) |
| NEW! Drill down into districts (local authorities) for a rural county | ![image](https://user-images.githubusercontent.com/5020841/92446442-bbc35b80-f1ad-11ea-948e-0bf95adffab1.png) |

# TODO list

(I don't think these block review/merging of this, it's spent long enough kicking around that I think getting eyes on the rest of the code is more important)

* [ ] The numbers on the top level library page ("Aberdeen City, Aberdeenshire, Angus, and 213 more…") are wrong
* [ ] Back button doesn't have context of how you got to a page. It always takes you `.../libraries`. As an immediate quick win, it could redirect you to `.../libraries/wd20-lad20-ctyua19`, but ideally it'd have a back link, like `/libraries/wd20-lad20-ctyua19/lad20-E07000008?prev_group_id=ctyua19-E10000003` which it could populate the back link from

2020-09-08 10:32 UTC, quis commented on app/broadcast_areas/repo.py
> +        if library_id == 'wd20-lad20-ctyua19':
You could make this generic by looking at the return value of
```
select broadcast_area_library_group_id from broadcast_areas where broadcast_area_library_id = ? limit 1
```

2020-09-08 10:34 UTC, quis requested changes
I think this needs tests for `GET` and `POST` on the new counties page, just to verify it’s showing the right list of things. Otherwise good to go, and thanks for splitting into decent commits.

Happy to leave the TODOs for separate PRs.

2020-09-08 10:44 UTC, leohemsted commented on app/broadcast_areas/repo.py
> +        if library_id == 'wd20-lad20-ctyua19':
as in "show me all areas in this library that have a parent"? Yeah that could work. i think this is the correct-est implementation:

```sql
select
exists(
  select *
  from broadcast_areas
  where broadcast_area_library_id = ? and
  broadcast_area_library_group_id is not null
)```

2020-09-08 10:57 UTC, quis commented on app/broadcast_areas/repo.py
> +        if library_id == 'wd20-lad20-ctyua19':
Yeah, that looks tidy. Does mean running two queries, but we only run these queries on app startup anyway so performance isn’t much of a concern.

2020-09-09 12:53 UTC, leohemsted commented
@quis tests squashed in to https://github.com/alphagov/notifications-admin/pull/3614/commits/b8fc46c7df9c3ac2186f5ce7e62b4d3f7acc8944

2020-09-09 13:57 UTC, quis approved these changes

2020-09-09 13:59 UTC, merged