Remove some of the option we have for broadcast services.
alphagov/notifications-admin pull request #3871
Opened 2021-05-05 13:15 UTC by servingUpAces

This is the first step in making the UI easier for setting the
options for a broadcast service. Here we remove the options for
"Training mode" test channels. When we create a broadcast message for a trail mode service it is marked as stubbed and does not create a broadcast event that is sent to a provider.

The label for the form and setting page have been updated to reflect the
change.

2021-05-05 13:28 UTC, quis requested changes
Some comments on the label next to the service name. Trying to keep it very short to fit in the minimal space we have, and also unambiguous (for example _Live - public channel_ sounds like there are other kinds of _Live_; there aren’t)

2021-05-05 13:28 UTC, quis commented on app/templates/views/service-settings.html
> +                {% if current_service.live and current_service.broadcast_channel == "severe" %}Live - Public channel{% endif %}
to follow my sketches this should be just _Live_
```suggestion
                {% if current_service.live and current_service.broadcast_channel == "severe" %}Live{% endif %}
```

2021-05-05 13:28 UTC, quis commented on app/templates/views/service-settings.html
> +                {% if current_service.live and current_service.broadcast_channel == "test" %}Test channel {% if current_service.allowed_broadcast_provider %}({{ current_service.allowed_broadcast_prov
And this should be _Test_, without the word _Network_ (it’s implicit that EE is a network)
```suggestion
                {% if current_service.live and current_service.broadcast_channel == "test" %}Test{% if current_service.allowed_broadcast_provider %}({{ current_service.allowed_broadcast_provider|format_mobile_network }}){% else %} (All networks){% endif %}{%endif%}
```

2021-05-05 13:28 UTC, quis commented on app/templates/views/service-settings.html
> +                {% if not current_service.live%}Training mode {% endif%}
aaaand this one should just be _Training_
```suggestion
                {% if not current_service.live%}Training{% endif%}
```

2021-05-06 07:18 UTC, servingUpAces commented
> Some comments on the label next to the service name. Trying to keep it very short to fit in the minimal space we have, and also unambiguous (for example _Live - public channel_ sounds like there are other kinds of _Live_; there aren’t)

Updates have been made to the labels.

2021-05-06 10:36 UTC, quis approved these changes

2021-05-06 10:43 UTC, idavidmcdonald commented
We should also check, definitely in production at the least, that we have no services that currently have these settings we are removing. Otherwise they will need to have their settings changed

2021-05-06 14:05 UTC, merged