Allow registering WebAuthn authenticators in memory
alphagov/notifications-admin pull request #3878
Opened 2021-05-11 13:54 UTC by benthorner

https://www.pivotaltracker.com/story/show/178066084

This adds basic functionality and infrastructure for registering
WebAuthn authenticators, using an in-memory store to keep the size
of the PR down. We can build on the patterns established here in
future PRs, and add more features:

- Hooking up with the API app
- Managing existing keys
- Dealing with server-side errors
- Authentication

**This PR is complicated.** I've tried to be as helpful as possible
in the code and commit messages, so have a look at those if you're
not sure about something. Most of the complexity is in the second
commit, where all the pieces can be seen working together.

2021-05-12 11:46 UTC, CrystalPea reviewed
Great work! 💖 

I left a few comments. Some are suggestions, some are just questions ☺️ 

Do we want to integrate with API in this PR? I think we could?


Also, H1 header seems to be a bit low here:
<img width="1045" alt="Screenshot 2021-05-12 at 11 11 55" src="https://user-images.githubusercontent.com/20957548/117969875-e3138f00-b31f-11eb-9b0c-d87aa07aae94.png">

2021-05-12 11:46 UTC, CrystalPea commented on app/webauthn_server.py
> +    app.webauthn_server.timeout = 10_000
when in the flow this timeout could happen?

If it's the time that user has to touch the key / make a decision, we could make it a bit longer, maybe 30 seconds? Otherwise it's ok 👍🏼

2021-05-12 11:46 UTC, CrystalPea commented on tests/app/main/views/test_webauthn_credentials.py
> +    # override base URL so it's consistent on CI and locally
should this comment go here, or above the mocking of the base URL?

2021-05-12 11:46 UTC, CrystalPea commented on tests/app/models/test_webauthn_credential.py
> +       'attestationObject': base64.b64decode(b'o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEgwRgIhAI1qbvWibQos/t3zsTU05IXw1Ek3SDApATok09uc4UBwAiEAv0fB/lgb5Ot3zJ691Vje6iQLAtLhJDiA8zDxaGjcE3hjeDVjgVkCUzCCAk8w
do we want to have this registration_response defined here, or would we want to hide it away since it's this long encoded string?

2021-05-12 11:46 UTC, CrystalPea commented on tests/app/models/test_webauthn_credential.py
> +       'attestationObject': base64.b64decode(b'o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEgwRgIhAI1qbvWibQos/t3zsTU05IXw1Ek3SDApATok09uc4UBwAiEAv0fB/lgb5Ot3zJ691Vje6iQLAtLhJDiA8zDxaGjcE3hjeDVjgVkCUzCCAk8w
Also do we want to present a decoded, readable version, to be able to visually compare with assertions?

2021-05-12 11:46 UTC, CrystalPea commented on tests/app/test_webauthn_server.py
> +def test_server_rp_id(
what is `rp`? Maybe we could have a bit more descriptive test name here?

2021-05-12 12:12 UTC, benthorner commented on app/templates/views/user-profile/security-keys.html
> +          Security keys are an alternative way of signing in to Notify.
I'm not sure, I just used the content from @quis. 

Since this is only for Platform Admins, I think we're OK without a content review for now.

2021-05-12 12:14 UTC, benthorner commented on app/assets/javascripts/registerSecurityKey.js
> +                alert('Error communicating with device.\n\n' + error.message);
No, this is all happening on the client side. We'd need to do another server request to get it into our logs, which would be unusual for JS code. While it's not ideal for remote debugging, we do log the full error object in the console and the alert, so we can always ask the user for it (and for now we're the only users anyway).

2021-05-12 12:18 UTC, benthorner commented on app/assets/javascripts/registerSecurityKey.js
> +      converters: { '* x-binary': (value) => value }
I did mention this in the commit message - it's [this StackOverflow article](https://stackoverflow.com/questions/12394622/does-jquery-ajax-or-load-allow-for-responsetype-arraybuffer) - but the comment is a bit hidden 😬.

- `dataType: 'x-binary'` is overriding jQuery's auto-detection.
- `converters: ...` is telling jQuery what to do with that data type.

We could probably use `'* text': ...` without the `dataType`, as I suspect that's what jQuery infers it as. I think it's better to be explicit, as the default jQuery behaviour is so "magical" (and not in a good way).

2021-05-12 12:24 UTC, benthorner commented on app/webauthn_server.py
> +    app.webauthn_server.timeout = 10_000
Yeah, this is [the timeout for the presence check](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/timeout).

Keeping it short makes testing the timeout easier, but we can always change it locally for testing. I originally thought 10 seconds would be enough, even for someone with a motor or visual impairment. Maybe not though if it's the first time they're seeing the dialogue. I've amended the second commit to use 30 seconds 👍.

2021-05-12 12:25 UTC, benthorner commented on app/main/views/webauthn_credentials.py
> +        user_verification="discouraged",
This is referring to [one of the authenticatorSelection settings](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/authenticatorSelection).

It means we don't require the user to setup a PIN, or other form of verification, on their authenticator. I've amended the second commit with a quick commit to hint at the meaning.

2021-05-12 12:27 UTC, benthorner commented on tests/app/main/views/test_webauthn_credentials.py
> +    # override base URL so it's consistent on CI and locally
Sort of, it applies to both: `init_app` needs to be called in order to pick up the change.

I've amended the second commit to move the comment and group the code together a bit more.

2021-05-12 12:32 UTC, benthorner commented on tests/app/models/test_webauthn_credential.py
> +       'attestationObject': base64.b64decode(b'o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEgwRgIhAI1qbvWibQos/t3zsTU05IXw1Ek3SDApATok09uc4UBwAiEAv0fB/lgb5Ot3zJ691Vje6iQLAtLhJDiA8zDxaGjcE3hjeDVjgVkCUzCCAk8w
The decoded version wouldn't be very useful, I'm afraid, as it's also CBOR-encoded. Even the CBOR-decoded version is pretty unreadable: it is a dict, but most of the values are still long byte sequences.

> would we want to hide it away

I was wondering if we had a place to put this sort of thing. It's basically a file fixture. I don't think it belongs in `conftest.py`, as it's only used once. On the other hand, I think it's OK in this file too.

Where do you think it could go instead?

2021-05-12 12:39 UTC, benthorner commented on tests/app/test_webauthn_server.py
> +def test_server_rp_id(
`rp` stands for "relying party", which isn't very intuitive but unfortunately that's the terminology used by the standard. Most of the WebAuthn docs I've seen use "rp" instead of "relying party". Since it relates to `rp.id` in the code, I don't think we should stray from this name; we just need to be familiar with WebAuthn. 

I've amended the second commit to expand it to `_relying_party_id(` in the tests.

2021-05-12 12:42 UTC, benthorner commented on tests/app/main/views/test_user_profile.py
> +    assert ' '.join(security_keys_row.text.split()) == 'Security keys 0 Change'
Sure, that's fair. I've amended the first commit for test for no keys and one key in the same test.

2021-05-12 12:52 UTC, benthorner commented
Thanks @CrystalPea! I've responded to all your comments; just a few left where I think there might be more to discuss.

> Do we want to integrate with API in this PR? I think we could?

We certainly could, but I decided not to because:

- I wanted to get this up for review quickly, and integrating the API will take more time.
- Integrating with that PR kind of blocks this one, or at least makes it more complicated to try out.
- We should be able to do the integration in parallel with other work, but only once this PR is merged.

> Also, H1 header seems to be a bit low here

I see what you mean. However, I checked against the other settings pages, and it's consistent with those. The one page it's _not_ consistent with is the platform admin one, where the heading is closer to the top because it uses [a different technique](https://github.com/alphagov/notifications-admin/blob/78824f54fdf7288172387f8ed3b332d26d74e083/app/templates/views/user-profile/disable-platform-admin-view.html#L22) to set the heading. We seem to have at least three different ways of putting a heading on a page in the Admin app, which is just bonkers! So I think we should leave it as-is, but maybe fix the "disable platform admin" page to be consistent.

2021-05-12 13:38 UTC, CrystalPea commented on app/templates/views/user-profile/security-keys.html
> +          Security keys are an alternative way of signing in to Notify.
ok 👍🏼

2021-05-12 13:40 UTC, CrystalPea commented on app/assets/javascripts/registerSecurityKey.js
> +      converters: { '* x-binary': (value) => value }
thanks!

2021-05-12 13:43 UTC, CrystalPea commented on tests/app/models/test_webauthn_credential.py
> +       'attestationObject': base64.b64decode(b'o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEgwRgIhAI1qbvWibQos/t3zsTU05IXw1Ek3SDApATok09uc4UBwAiEAv0fB/lgb5Ot3zJ691Vje6iQLAtLhJDiA8zDxaGjcE3hjeDVjgVkCUzCCAk8w
Hmmm you are right we don't have an optimal place to put it. Maybe at the top of the file as a constant? I think we have put some bulky things at top of file like that in other places.

2021-05-12 13:44 UTC, CrystalPea commented on tests/app/test_webauthn_server.py
> +def test_server_rp_id(
I think that expansion helps, because we have it as "relying_party" elsewhere in the code, thanks!

2021-05-12 13:47 UTC, CrystalPea commented
> I wanted to get this up for review quickly, and integrating the API will take more time.
Integrating with that PR kind of blocks this one, or at least makes it more complicated to try out.
We should be able to do the integration in parallel with other work, but only once this PR is merged.
Also, H1 header seems to be a bit low here

Fair, we can do it separately that's true.

> I see what you mean. However, I checked against the other settings pages, and it's consistent with those. The one page it's not consistent with is the platform admin one, where the heading is closer to the top because it uses a different technique to set the heading. We seem to have at least three different ways of putting a heading on a page in the Admin app, which is just bonkers! So I think we should leave it as-is, but maybe fix the "disable platform admin" page to be consistent.

I think it would be up to @quis to decide which way the consistency should go, from visual standpoint, no?

2021-05-12 13:54 UTC, tombye requested changes
I read most of the code, to understand what was happening, but kept my review to the frontend bits.

I've left some comments on a few things but this looks good.

The only largish thing I noticed was the lack of states for users without JS and those whose devices/browsers don't support web auth. We've chatted about how to message users in those scenarios out of this pull request so the work is planned but worth mentioning it here as a record of that.

2021-05-12 13:54 UTC, tombye commented on app/assets/javascripts/registerSecurityKey.js
> +    var xhrOverride = new XMLHttpRequest();
Looking at the support for [window.fetch]() and the [web auth API](https://caniuse.com/webauthn), we could assume fetch is available if web auth is. You mentioned in your commit adding this code that fetch would be preferred so this might be an opportunity to use it instead.

In my opinion, it would be useful to:
- not have to have a hack to make `$.ajax` work
- not use a 'promise-like' thing like `$.ajax` with actual Promises if we can help it

2021-05-12 13:54 UTC, tombye commented on app/assets/javascripts/registerSecurityKey.js
> +      data: CBOR.encode({
Would be nice to use `window.CBOR` here, to match your use on line 12
```suggestion
      data: window.CBOR.encode({
```

2021-05-12 13:54 UTC, tombye commented on tests/javascripts/registerSecurityKey.test.js
> +    Object.defineProperty(window.navigator, 'credentials', {
This and the other blocks that redefine DOM APIs should really have their original values reset after the test that uses them. Just to avoid any unexpected side effects in tests that run after these.

2021-05-12 13:54 UTC, tombye commented on tests/javascripts/registerSecurityKey.test.js
> +    jest.spyOn(window.$, 'ajax').mockImplementation((options) => {
This and other mocked spies should be reset after their test is run, to avoid any unexpected cases in future tests.

2021-05-12 13:54 UTC, tombye commented on tests/javascripts/registerSecurityKey.test.js
> +      done()
Jest's docs have `done` as the last line of code run, after any assertions, so we should probably do the same.

See: https://jestjs.io/docs/asynchronous#callbacks

2021-05-12 16:47 UTC, benthorner commented on app/assets/javascripts/registerSecurityKey.js
> +    var xhrOverride = new XMLHttpRequest();
Definitely, great idea! It's quite a big change, so I've added a couple more commits to switch to `fetch` (the 4th and 5th commits). How does it look now?

2021-05-12 16:47 UTC, benthorner commented on app/assets/javascripts/registerSecurityKey.js
> +      data: CBOR.encode({
Sure, I've amended the second commit to do that 👍.

2021-05-12 16:49 UTC, benthorner commented on tests/javascripts/registerSecurityKey.test.js
> +    Object.defineProperty(window.navigator, 'credentials', {
That makes sense. It kind of slipped my mind (/we don't seem to do it [in other tests](https://github.com/alphagov/notifications-admin/blob/78824f54fdf7288172387f8ed3b332d26d74e083/tests/javascripts/enhancedTextbox.test.js#L282)). In the 4th commit and onwards, I've shifted the test code to restore original values (if there were any).

How does it look now?

2021-05-12 16:50 UTC, benthorner commented on tests/javascripts/registerSecurityKey.test.js
> +    jest.spyOn(window.$, 'ajax').mockImplementation((options) => {
Yup, I've addressed this as part of https://github.com/alphagov/notifications-admin/pull/3878#discussion_r631222693.

I'll resolve this one and we can continue any further discussion there.

2021-05-12 16:54 UTC, benthorner commented on tests/javascripts/registerSecurityKey.test.js
> +      done()
Good spot, that makes sense. I accidentally put the fix in the 4th commit, but it's not a big change so I'll leave it there and just mention it in the commit message.

2021-05-12 17:17 UTC, benthorner commented
Thanks for the review @tombye 💯. I think I've addressed all your comments.

> the lack of states for users without JS and those whose devices/browsers don't support web auth

We do indeed have a plan to address this: I've made a note to do it as part of the card for this PR. It should be a quick, best practice thing to implement, so we should just do it (vs. saying it's not MVP and then forgetting).

> I think it would be up to @quis to decide which way the consistency should go, from visual standpoint, no?

@CrystalPea I guess it is. However, I think that's out-of-scope for this PR: once we make a decision, we'll need to change at least one other HTML file to make them consistent. The new HTML file is consistent with four other HTML files, so I'm not introducing anything new here. I'm happy to make all of them consistent in a follow-up PR, so we have fewer ways of doing headings 😄. But I don't think it should block this one going in.

2021-05-13 08:28 UTC, benthorner commented on tests/app/models/test_webauthn_credential.py
> +       'attestationObject': base64.b64decode(b'o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEgwRgIhAI1qbvWibQos/t3zsTU05IXw1Ek3SDApATok09uc4UBwAiEAv0fB/lgb5Ot3zJ691Vje6iQLAtLhJDiA8zDxaGjcE3hjeDVjgVkCUzCCAk8w
Sure, I've amended the second commit with the data in constant at the top. I realised the `clientDataJSON` is quite readable when decoded, so I've swapped it for that. I've moved the session data up there two, since the three pieces of data need to match / go together.

I guess having it at the top is easier to read if you have wrapping turned on in your editor.

How does it look now?

2021-05-13 08:37 UTC, klssmith commented on requirements.txt
> +cryptography==3.4.7
If we need a version of cryptography that's > 3.4 we'll need to work out how to get round the build failing on the PaaS due to not having Rust installed

2021-05-13 09:26 UTC, CrystalPea commented on tests/app/models/test_webauthn_credential.py
> +       'attestationObject': base64.b64decode(b'o2NmbXRoZmlkby11MmZnYXR0U3RtdKJjc2lnWEgwRgIhAI1qbvWibQos/t3zsTU05IXw1Ek3SDApATok09uc4UBwAiEAv0fB/lgb5Ot3zJ691Vje6iQLAtLhJDiA8zDxaGjcE3hjeDVjgVkCUzCCAk8w
Thank you, looks good 👍🏼

2021-05-13 09:27 UTC, CrystalPea approved these changes

2021-05-13 09:39 UTC, karlchillmaid commented on app/templates/views/user-profile/security-keys.html
> +          Security keys are an alternative way of signing in to Notify.
Agree. I'll review another time

2021-05-13 09:42 UTC, benthorner commented on requirements.txt
> +cryptography==3.4.7
Nice spot / save! I've amended the second commit to pin it below 3.4 and explained why in comments. Deploying to Preview shows it works 🎉  (with a bit of variability, since we're using an in-memory store that's not shared between the two instances running in Preview).

2021-05-13 10:12 UTC, tombye commented on tests/javascripts/registerSecurityKey.test.js
> +  test.each([
This is a really nice way of describing the different error states 👍🏻

2021-05-13 10:15 UTC, tombye commented on app/assets/javascripts/registerSecurityKey.js
> +    var xhrOverride = new XMLHttpRequest();
Looks great, and the code and tests seem to describe the various scenarios a lot better I think 👍🏻

2021-05-13 10:17 UTC, tombye commented on tests/javascripts/registerSecurityKey.test.js
> +    Object.defineProperty(window.navigator, 'credentials', {
That test without them you spotted should also have them. I'll put a fix up soon but do say if you know of any others.

This looks good now.

2021-05-13 10:23 UTC, benthorner commented on tests/javascripts/registerSecurityKey.test.js
> +    Object.defineProperty(window.navigator, 'credentials', {
Thanks!

> That test without them you spotted should also have them.

I think it's done already: that test [also calls `teardown.js`](https://github.com/alphagov/notifications-admin/blob/78824f54fdf7288172387f8ed3b332d26d74e083/tests/javascripts/enhancedTextbox.test.js#L8), which is where I added the hook.

2021-05-13 10:23 UTC, tombye commented on app/assets/javascripts/registerSecurityKey.js
> +      $(component)
I should have mentioned this before but can we put in a guard at the top to make it return if the needed web APIs aren't available?
```suggestion
      if (!('fetch' in window) || !('credentials' in window.navigator)) { return }
      $(component)
```

2021-05-13 10:26 UTC, benthorner commented on app/assets/javascripts/registerSecurityKey.js
> +      $(component)
We did [discuss it before](https://github.com/alphagov/notifications-admin/pull/3878#pullrequestreview-657903585), but not from a JS point of view. I'll leave it as-is for now, and make it part of the follow-up PR so it's all in one place (I've made a not of your suggested change on the card).

2021-05-13 10:27 UTC, tombye commented
@benthorner I'm happy all my comments have been addressed. I added [an extra one](https://github.com/alphagov/notifications-admin/pull/3878#discussion_r631712899), sorry 😬, which the chat with you about browser support/fallbacks made me realise was needed. Everything else is 💯 so thanks for all the work.

2021-05-13 10:37 UTC, tombye approved these changes

2021-05-13 11:25 UTC, klssmith commented
I was happy with this too. I just had one question - when Chrome gives you the "Allow this site to see your security key?" window are we saving exactly the same data when someone clicks "Skip" vs when they click "Allow"?

2021-05-13 11:42 UTC, benthorner commented
Thanks all, it's time merge! 🎉

> I just had one question - when Chrome gives you the "Allow this site to see your security key?" window are we saving exactly the same data when someone clicks "Skip" vs when they click "Allow"?

Good spot @klssmith! I ran a few tests locally and clicking "Skip" means (referring to [the API docs](https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAttestationResponse)):

- `authData.attestedCredentialData.aaguid` is set to `00000000000000000000000000000000` (masking the make/model).
- `fmt` is `none`, which goes with...
- `attStmt` is `{}`

If we verified attestation in future, then this wouldn't be allowed through. And it would be a red flag if we ever audit the credentials. For now I think it's OK to request `direct` attestation, and allow people to opt-out.

2021-05-13 11:43 UTC, merged