Add utility function to aggregate alert areas
alphagov/notifications-admin pull request #4003
Opened 2021-08-24 16:21 UTC by benthorner

https://www.pivotaltracker.com/story/show/178986763

Shamelessly based on #3980. @quis did all the prototyping
work, and this PR massages it into a more maintainable form.

As written on the other PR, we need a means to aggregate
areas for a broadcast because:

- electoral ward names (one level of area) aren't meaningful
- the list of areas may be very long

A secondary concern is applying this to custom polygons. We're
not sure if this code will get applied to messages submitted
via the API, which can have their own area descriptions. Adding
support for it now has two benefits:

- It makes it easier to test the approach on larger regions by
using coordinates instead of listing all the wards.

- It helps ensure we're forwards compatible with applying it to
API polygons, or even custom ones created in this app.

@quis recommended [this diagram](https://www.ons.gov.uk/methodology/geography/ukgeographies/administrativegeography/england) to understand the structure of UK authorities.

2021-08-24 16:25 UTC, benthorner commented
I've also tested this against all historical broadcasts ([gist](https://gist.github.com/benthorner/5483e335b592d00dd3a16e1cd9560d11)):

- All UK broadcast areas were aggregated with no errors ✅.
- Overall, the aggregation cuts 741 areas down to 492 🚀.

Although most of the historical messages are non-realistic, running them through the aggregation and inspecting the output gives me more confidence it will produce meaningful results in a variety of scenarios.

2021-08-25 16:39 UTC, CrystalPea requested changes
Hey, good job, that was nice to read through and review 👏🏼 

I spotted something that may be a little mistake, and then there are a couple smaller comments / asks for clarification.

I also have one more general comment: when we aggregate wards into a larger area, but the wards do not represent the full area, should we not add `parts of`? Otherwise people may be wondering why they didn't get the broadcast even though they are in this area.

So for example if message was sent to `Hackney Wick` and `Hackney Marshes`, and we aggregate that to `Hackney`, wouldn't people from `Hackney Central` be potentially confused? But if we say `parts of Hackney`, that's more accurate, and together with the map would work pretty well. What do you think?

2021-08-25 16:39 UTC, CrystalPea commented on app/broadcast_areas/utils.py
> +        area.parent if area.id.startswith('wd20-')
Optional: could be useful explaining in an inline comment why we look specifically for parents of areas starting with `wd20-`. I see it's explained in the tests that this signifies electoral wards, but might be also useful to have the explanation where the code is.

2021-08-25 16:39 UTC, CrystalPea commented on app/broadcast_areas/utils.py
> +            results |= set(area.overlapping_electoral_wards)
fun, haven't seen `ior` operator before :D

In case anybody later is reading later and wondering, here is a good explanation: https://stackoverflow.com/questions/3929278/what-does-ior-do-in-python

2021-08-25 16:39 UTC, CrystalPea commented on app/broadcast_areas/utils.py
> +        elif len(clusters) > 1:
shouldn't it be `cluster` instead of `clusters` on this line?

2021-08-25 16:39 UTC, CrystalPea commented on app/broadcast_areas/utils.py
> +            results |= {area.parent or area}
I'm not sure what we are doing here, could use some help please.

2021-08-25 16:39 UTC, CrystalPea commented on app/broadcast_areas/utils.py
> +        else:
what condition would meet this `else`? It feels like all the cases were matched above 🤔

2021-09-02 08:56 UTC, quis commented on tests/app/broadcast_areas/test_models.py
> +    ]) == expected_wards_length
The list comprehension isn’t adding anything here – this assertion is equivalent:
```suggestion
    assert len(custom_area.overlapping_electoral_wards) == expected_wards_length
```

2021-09-02 08:58 UTC, quis commented on tests/app/broadcast_areas/test_utils.py
> +            # in Gloucestershire (upper tier authority)
```suggestion
            # Area covers lower-tier authorities in
            # Gloucestershire and Oxfordshire (both
            # upper tier authorities)
```

2021-09-02 11:56 UTC, benthorner commented on tests/app/broadcast_areas/test_models.py
> +    ]) == expected_wards_length
Good spot! I've amended the first commit with that.

2021-09-02 12:01 UTC, benthorner commented on tests/app/broadcast_areas/test_utils.py
> +            # in Gloucestershire (upper tier authority)
Oops, thanks for spotting.

I've updated with [something slightly more specific](https://github.com/alphagov/notifications-admin/pull/4003/commits/bcfa21428f3161b1e3964671d1ffda720c71b358#diff-7ccef2c9a90607cf55d1b7a1bbce444014a3b8e2c1a70bde2eed43a0fe871daeR151).

2021-09-02 12:14 UTC, merged