If a templated letter that has been posted by the API and has over 10…
alphagov/notifications-admin pull request #4107
Opened 2021-12-22 10:32 UTC by servingUpAces

… pages show the validation status and letter-too-long message

2022-01-27 11:12 UTC, CrystalPea commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
> The letter is not in validation failed, this will enable us to show the error

why is the letter not in validation failed?

2022-01-27 11:30 UTC, servingUpAces commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
The letter is in validation-failed. 
The trouble with this page is that it doesn't get the file from S3, which does have the metadata with the error message. Instead it uses a preview of the letter using template-preview. This is why I had to check the page count in this way. 
I am open to other options, do you have any ideas?

2022-01-27 11:35 UTC, leohemsted commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
hmmmm, why aren't we getting the file from s3? we put it in the `letters-invalid-pdf` bucket with metadata attached in your template preview PR

2022-01-27 11:36 UTC, servingUpAces commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
Would this code be more clear if I add a `if validation-failed` statement?

2022-01-27 11:39 UTC, servingUpAces commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
Only trouble with adding that statement is that it could take time to go to validation-failed because the template-preview app has to first create the pdf, then call a task in API to update the status of the notification. Without the `if validation-failed` the user could see the failure as soon as the notification is uploaded.

2022-01-27 12:08 UTC, CrystalPea commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
I think it's ok (although downloading file and metadata from S3 would be even better = one source of truth), I'd change the comment to be more clear though, maybe something like:

```
when a templated letter is sent via the api and the personalisation pushes the page count over 10 pages, it takes a while for validation status to come through. Checking page count here will enable us to show the error even if the letter is not in validation failed yet.
```

2022-01-27 12:57 UTC, leohemsted commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
i think this whole function could be really refactored, at least the letter part of it. I found it pretty hard to follow and confusing as to why there's all these separate blocks. (i also _really_ don't like how admin is parsing precompiled PDFs for its page count itself if there isn't info in the metadata, but that's a separate issue). There's other stuff I don't understand like "why are we modifying the notification['template']['postage'] rather than reading from the notification itself". I think we could shake this whole block up by starting again from what we actually need and laying it out sensible.

But that said, i don't think that needs to block this PR going in, and I think pea's comment change is a great suggestion.

2022-01-28 17:46 UTC, CrystalPea requested changes
Hey, good work fixing this bug. 

I found the comment was unclear, and maybe it would fit in better as a part of commit message?

I rewrote it a bit, let me know what you think.

2022-01-28 17:46 UTC, CrystalPea commented on app/main/views/notifications.py
> +            # When a templated letter is sent via the api and the personalisation pushes
This comment still feels a bit chaotic. It mostly explains why we went for this solution - that would really fit better as a part of commit message.

Also the part that explains validation process for templated API letters doesn't state how this is connected with the decision to count pages here.

I spent some time on this, I hope I arrived at something that can satisfy us both. Up to you if you'd rather have it inline with the code, or as a "WHY" part in the commit message ☺️ .


> We check page count here to show the right error message for a letter that is too long. Another way to do this would be to get the status and error message from letter metadata. This would be a significant amount of work though, out of scope for this bug fix. This is because currently we do not pull the letter from S3 when showing preview. Instead, we generate letter preview based on the letter template and personalisation.
> Additionally, when a templated letter is sent via the api and the personalisation pushes the page count over 10 pages, it takes a while for validation status to come through. Checking page count here will enable us to show the error message even if the letter is not fully processed yet.

2022-01-31 10:02 UTC, servingUpAces commented on app/main/views/notifications.py
> +            # the page count over 10 we need to validate that. The letter is not in validation failed,
Yes I agree that it would be better to refactor this whole page, and I don't like how I had to update the page to get the validation error to show. 
However, I would like to put this in to complete the story and look at the large refactor at another time.

2022-02-01 10:12 UTC, CrystalPea approved these changes

2022-02-02 07:58 UTC, merged