Add pages to generate a government identity system logo
alphagov/notifications-admin pull request #4394
Opened 2022-10-21 16:19 UTC by quis

Test locally at http://localhost:6012/email-branding/create-government-identity?text=Government%20Digital%20Service

<img width="764" alt="image" src="https://user-images.githubusercontent.com/355079/197242301-dff82fdb-2b2c-4797-b6ad-4c86df03321b.png">

<img width="761" alt="image" src="https://user-images.githubusercontent.com/355079/197242374-d0101b66-60d9-4a38-9783-2a2581907ae9.png">

<img width="768" alt="image" src="https://user-images.githubusercontent.com/355079/197242406-93a3c342-b72e-45f4-b08a-f0a18080d0ae.png">

2022-11-02 17:49 UTC, CrystalPea requested changes
Good work, this will make setting the government logo much easier for the admins 👏🏼 

I left some comments.

Also, I gather integrating this picker with the Zendesk ticket should be a separate PR and story? I will create a story for this in Trello 👍🏼

2022-11-02 17:49 UTC, CrystalPea commented on tests/app/main/views/test_email_branding.py
> +    ] == [
This is a very busy assertion, a bit hard to follow. It would help if we defined sides of the assertion as variables and then compared those. Like:

```
expected_stripes_options = [all the stripes options]

radios_on_the_page = [ the comprehension list for getting radio labels ]

assert radios_on_the_page ==  expected_stripes_options
```

We could do the same for crests, too.

2022-11-02 17:49 UTC, CrystalPea commented on app/main/forms.py
> +def markup_for_crest_or_insignia(filename):
Is there advantage to defining this markup here as opposed to the template? 

Asking since it feels more naturally at home in the template.

2022-11-02 17:49 UTC, CrystalPea commented on app/templates/views/email-branding/government-identity-options-colour.html
> +  {{ '{} email branding'.format('Update' if email_branding else 'Add')}}
same here, don't we create a new branding each time as it is?

2022-11-02 17:49 UTC, CrystalPea commented on app/templates/views/email-branding/government-identity-options-colour.html
> +  {{ page_header('{} email branding'.format('Update' if email_branding else 'Add')) }}
It would be good to define content for page title and header once only, and then pass that variable. @samuelhwilliams has shown me recently that this also can be done using form's field label (like [here](https://github.com/alphagov/notifications-admin/blob/master/app/templates/views/service-settings/branding/add-new-branding/government-branding-or-own-logo.html#L10))

2022-11-02 17:49 UTC, CrystalPea commented on tests/app/main/views/test_email_branding.py
> +def test_create_email_branding_government_identity_colour_400_if_no_filename(
Could we rename this to `test_create_email_branding_government_identity_colour_400_if_no_filename_or_file_doesnt_exist` ?

2022-11-02 18:00 UTC, samuelhwilliams commented on app/main/forms.py
> +        validators=[DataRequired()],
I think we actually don't want this validator when using GovukRadiosField. I discovered recently that this changes the error message shown when no option is selected from 'Select an option' to 'Cannot be empty' - I think we prefer the former?

2022-11-02 18:02 UTC, samuelhwilliams commented on app/models/branding.py
> +GOVERNMENT_IDENTITY_SYSTEM_COLOURS = [
I also think the list-of-dicts structure is slightly verbose here. Could we not just have it be a dict of `{"org_name": "#aabbcc", ...}`?

2022-11-02 18:14 UTC, CrystalPea reviewed
I [added a story](https://trello.com/c/kneFiwYk/98-integrate-crest-picker-with-the-zendesk-ticket) for the integration with Zendesk now.

2022-11-03 09:33 UTC, quis commented on app/main/views/email_branding.py
> +            email_safe(filename),
Yes, for example https://static-logos.notifications.service.gov.uk/e688b983-a2ed-4985-a1b6-9e770de1d175-blaby.png

2022-11-03 09:37 UTC, quis commented on app/models/branding.py
> +GOVERNMENT_IDENTITY_SYSTEM_COLOURS = [
Changed to a `dict` in 6e984bbf32004ab3bd0adbe7403d243640f017df

Personally I feel like models are the place to get data about a specific domain. Sometimes that’s from the API, sometimes from the filesystem, sometimes hardcoded.

For me a utils are more like for standalone functions which take primitive data types as arguments. But that distinction might just be in my head 🤷🏻

2022-11-03 09:48 UTC, quis commented on app/main/forms.py
> +def markup_for_crest_or_insignia(filename):
I don’t think there’s an easier way to inject HTML into the field labels now that we’re using the componentised form fields.

2022-11-03 10:08 UTC, quis commented on app/templates/views/email-branding/government-identity-options-colour.html
> +  {{ page_header('{} email branding'.format('Update' if email_branding else 'Add')) }}
I’ve fixed the page titles by using the form label instead: e35272e64cf33bdc0c527f9c959362310cf0d494

2022-11-03 10:08 UTC, quis commented on app/templates/views/email-branding/government-identity-options-colour.html
> +  {{ '{} email branding'.format('Update' if email_branding else 'Add')}}
I’ve fixed the page titles by using the form label instead: e35272e64cf33bdc0c527f9c959362310cf0d494

2022-11-03 10:08 UTC, quis commented on app/main/forms.py
> +        validators=[DataRequired()],
Made the validation better in defd96540c01742a99b277506200a45010184394

2022-11-03 10:09 UTC, quis commented on tests/app/main/views/test_email_branding.py
> +def test_create_email_branding_government_identity_colour_400_if_no_filename(
```suggestion
def test_create_email_branding_government_identity_colour_400_if_no_filename_or_file_doesnt_exist(
```

2022-11-03 10:11 UTC, quis commented on app/templates/views/email-branding/government-identity-options.html
> +  {{ '{} email branding'.format('Update' if email_branding else 'Add')}}
I’ve fixed the page titles by using the form label instead: e35272e64cf33

2022-11-03 10:20 UTC, quis commented on app/main/views/email_branding.py
> +        upload_filename = upload_email_logo(
Yes, but this seems to be the way the existing page works. It goes through these steps:
- upload the logo
- page submits the form automatically and logo is stored to S3 with a ‘temporary’ file name
- form is submitted again with text and colour fields filled in
- logo is re-uploaded with a new ‘temporary’ file name
- old temporary logo is deleted
- new temporary logo is copied to the same bucket but with a permanent file name
- new temporary logo is deleted

It’s a mess but:
- at least we’re not storing duplicates permanently
- fixing it is definitely outside the scope of this story

2022-11-03 10:55 UTC, quis commented on tests/app/main/views/test_email_branding.py
> +    ] == [
Refactored in aa084100dae14e379a3252cd634eb83fd29097ac

2022-11-03 11:51 UTC, CrystalPea commented on app/main/views/email_branding.py
> +            email_safe(filename),
Ahhh, interesting, thanks!

2022-11-03 11:56 UTC, CrystalPea commented on app/main/views/email_branding.py
> +        upload_filename = upload_email_logo(
I had no idea this is how it's currently working, wow 🤯. But I guess if they are temporary maybe it's not that bad. We can look at it when doing clean up at the finish line for this epic.

2022-11-03 12:02 UTC, CrystalPea commented on app/templates/views/email-branding/government-identity-options-colour.html
> +  {{ '{} email branding'.format('Update' if email_branding else 'Add')}}
Nice one 👏🏼

2022-11-03 12:15 UTC, CrystalPea commented on app/models/branding.py
> +GOVERNMENT_IDENTITY_SYSTEM_COLOURS = [
I see what you mean. I think it would also go well in app/utils/branding.py, but also I don't feel strongly about this, and I think both perspectives have merit, so I resolved this convo 👍🏼

2022-11-03 12:15 UTC, CrystalPea approved these changes
Looks good to me

2022-11-03 13:44 UTC, merged