Add page for choosing an email banner type
alphagov/notifications-admin pull request #4412
Opened 2022-10-31 19:11 UTC by samuelhwilliams

## Summary
Adds a page to the middle of the "request a new email brand" flow where users can decide whether they want a plain logo or a block-colour background behind their logo.

We add a new form field type `ImageRadioField` that tries to separate out the logic and templating required to show images as part of the label for a given radio option. It adds a second `label` element to each `input`, which is [semantically allowed](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attributes): "Multiple label elements can be given the same value for their for attribute; doing so causes the associated form control (the form control that `for` value references) to have multiple labels." This allows clicking on the image to select the related option.

## Images
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/2920760/199089950-074523a5-c2d5-48b6-b59c-e18fcc39afe9.png">

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/2920760/199090006-ca29fd32-e8bb-4798-b900-9d0e59e35e85.png">

## Ticket
https://trello.com/c/GDnrFbse/69-build-the-page-where-a-user-can-choose-if-they-want-a-banner-or-not

2022-10-31 19:12 UTC, samuelhwilliams commented on tests/app/main/views/service_settings/test_service_settings.py
> +        ("local", 404),
Expecting this test to fail for now - waiting for merge of https://github.com/alphagov/notifications-admin/pull/4401 that adds the appropriate decorator.

2022-11-01 17:56 UTC, samuelhwilliams commented
Not sure this `ImageRadioField` implementation is any good actually :( Need to think about it some more. I reckon the macros it's using are outdated - they're not using proper design system classes... 💩

2022-11-02 08:04 UTC, samuelhwilliams commented
@tombye have refreshed the implementation for rendering radios with images in 6372c4df64b24dff83a70ec497bdb13744f089f9... But would be good to get your thoughts/chat to you about whether we need to do something different? I've basically fully vendored the radios implementation in order to insert an extra label, so as/when we upgrade to DS3/4 we might need to manually update this template for now (or replace it entirely if we get native python macros).

The final render using this commit's radio field is this:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/2920760/199433157-66d8795b-bfaa-442c-91c0-c378c8a84384.png">

I am not tackling the use-case that Chris has in [his PR](https://github.com/alphagov/notifications-admin/pull/4394) as I think his way of doing it as part of the choice 'text' is probably cleaner, in reality.

2022-11-08 16:29 UTC, CrystalPea requested changes
Wow, definitely an example of when a small story became a big one. Well done for persevering with it and implementing a new accessible component 👏🏼 

I left some comments.

2022-11-08 16:29 UTC, CrystalPea commented on app/templates/forms/fields/radios-with-hero/template.njk
> +  A minimally-modified copy of the radios component from v3.0.0 of the Design System
How do we make sure we keep this component up to date, if we fork it like this?

EDIT: I see we have a test for that, nice one 👏🏼

2022-11-08 16:29 UTC, CrystalPea commented on app/templates/views/service-settings/branding/add-new-branding/email-branding-choose-banner.html
> +{% set page_title = 'Add a banner to your logo' %}
could we do

```

{% block service_page_title %}
  {{ form.banner.label.text }}
{% endblock %}
```

here, to have the title defined once only?

2022-11-08 16:29 UTC, CrystalPea commented on tests/app/main/views/service_settings/test_service_settings.py
> +def test_only_central_org_services_can_see_email_branding_choose_banner_type_page(
Everyone should be able to choose banner type. 

Should we test that a central and local org both can access the endpoint?

2022-11-08 16:29 UTC, CrystalPea commented on tests/app/main/views/service_settings/test_service_settings.py
> +def test_email_branding_choose_banner_type_redirects_to_right_page(
Since it's the first time we are using a new component, should we maybe test that errors appear twice (in summary and by radios) if no option is selected?

2022-11-08 18:12 UTC, leohemsted requested changes
Sorry, I feel like a dick but i really would like you to update the template to be jinja2 rather than nujucks now that we've merged most of the updates to remove nunjucks from our codebase 😶

2022-11-08 18:12 UTC, leohemsted commented on tests/templates/components/test_radios_with_hero.py
> +        "`app/templates/forms/fields/radios-with-hero/template.njk` is a structurally-correct amd up-to-date macro. "
```suggestion
        "templates redefined in `govuk_frontend_jinja_overrides` are structurally correct and up-to-date"
```

2022-11-08 18:12 UTC, leohemsted commented on tests/templates/components/test_radios_with_hero.py
> +def test_radios_with_hero_on_design_system_v2():
we're already on 3.0.0

```suggestion
def test_radios_with_hero_on_design_system_v3():
```

2022-11-08 18:12 UTC, leohemsted commented on app/main/forms.py
> +class GovukRadiosFieldWithHero(GovukRadiosField):
i cant add a ➕ in github, but just echoing that i did some googling around "hero web component" and searches like that and found stuff that doesn't quite match up with what we're doing here (mostly about a splash page image eg https://www.optimizely.com/optimization-glossary/hero-image), so i'd be open to a name change here.

`GovukRadiosWithLargeImageField` or something?

2022-11-08 18:21 UTC, leohemsted commented on app/main/forms.py
> +class GovukRadiosFieldWithHero(GovukRadiosField):
i cant add a ➕ in github, but just echoing that i did some googling around "hero web component" and searches like that and found stuff that doesn't quite match up with what we're doing here (mostly about a splash page image eg https://www.optimizely.com/optimization-glossary/hero-image), so i'd be open to a name change here.

`GovukRadiosWithLargeImageField` or something?

2022-11-09 08:48 UTC, samuelhwilliams commented on app/main/forms.py
> +class GovukRadiosFieldWithHero(GovukRadiosField):
Yep, hero is a holdover from the original draft so will rename to GovukRadiosWithLargeImageField 👍

2022-11-09 09:07 UTC, samuelhwilliams commented on app/main/forms.py
> +class GovukRadiosFieldWithHero(GovukRadiosField):
Addressed in 091b994fb

2022-11-09 09:08 UTC, samuelhwilliams commented on app/main/forms.py
> +    # this bypasses that by making self.widget a method with the same interface as widget.__call__
This little snippet/explanation is copy/pasted all over the place 😳 It's in this file about 10 times 😬 

Maybe that's a sign we should fix something ... but not as part of this ticket 😬

2022-11-09 09:09 UTC, samuelhwilliams commented on app/main/forms.py
> +def markup_for_banner_image(url, alt_text):
💥 

It's gone!

This way of doing things disappeared at some point in the build process, either in my own component or the design system upgrades 😬  It's been a slog. Good spot.

2022-11-09 09:10 UTC, samuelhwilliams commented on app/main/forms.py
> +                "alt_text": 'A blank email with the heading "Your logo" in blue text on a white background.',
Nope - by all means @karlchillmaid, please review :)

2022-11-09 09:10 UTC, samuelhwilliams commented on app/main/forms.py
> +                "dimensions": {"width": 404, "height": 454},
Setting the dimensions is an optimisation suggested by @tombye - it helps the browser reserve the space before the image is loaded, so that the page can be layout correctly immediately and doesn't pop/jump around when the images are loaded later.

2022-11-09 09:11 UTC, samuelhwilliams commented on app/main/views/service_settings.py
> +@service_belongs_to_org_type("central")
Removed in 00f37ab89f47959533aa7827bfafb5d93d6e98be

2022-11-09 09:24 UTC, samuelhwilliams commented on tests/app/main/views/service_settings/test_service_settings.py
> +def test_email_branding_choose_banner_type_redirects_to_right_page(
Added in 639b013e96adcd7f1fbf08d5a058590555aefdf9

2022-11-09 09:25 UTC, samuelhwilliams commented on tests/templates/components/test_radios_with_hero.py
> +def test_radios_with_hero_on_design_system_v2():
meh I already bumped this and it must've got lost, changes incoming

2022-11-09 09:26 UTC, samuelhwilliams commented on app/templates/forms/fields/radios-with-hero/template.njk
> +  Blob permalink: https://raw.githubusercontent.com/alphagov/govuk-frontend/99077a036aeabb24aef5f741daeb93ea2ccdd99e/src/components/radios/template.njk
Yep, will do

2022-11-09 12:54 UTC, samuelhwilliams commented
I have now squashed all of the commits down @leohemsted @CrystalPea

2022-11-09 15:35 UTC, CrystalPea commented on app/main/forms.py
> +                "dimensions": {"width": 404, "height": 454},
Ahh, cool!

2022-11-09 15:36 UTC, CrystalPea commented on app/main/forms.py
> +class GovukRadiosFieldWithHero(GovukRadiosField):
Nice one 👏🏼

2022-11-09 15:38 UTC, CrystalPea commented on app/main/forms.py
> +    # this bypasses that by making self.widget a method with the same interface as widget.__call__
Ahh, ok, so we just proliferated it here, not written it? If so, is it necessary to add it at all, if it's so cryptic?

2022-11-09 15:41 UTC, CrystalPea approved these changes
Nice one!

Ready to ship once it's got a content pass from Karl ☺️

2022-11-09 15:50 UTC, karlchillmaid commented on app/main/forms.py
> +                "alt_text": 'A blank email with the heading "Your logo" in blue text on a white background.',
GOV.UK alt text guidance says:

>Good alt text states what an image means. It is not a description of the image itself.

If we follow that, we could probably change this alt text a little to make it more about what the image means, than what it looks like.

I’ll give this some thought. 💭

2022-11-09 15:52 UTC, karlchillmaid commented on app/main/forms.py
> +                "alt_text": 'A blank email with the heading "Your logo" in blue text on a white background.',
```suggestion
                "alt_text": 'An example of an email with a logo on a blank background.',
```

2022-11-09 15:53 UTC, karlchillmaid commented on app/main/forms.py
> +                "alt_text": 'A blank email with the heading "Your logo" in white text on a blue banner background.',
```suggestion
                "alt_text": 'An example of an email with a logo on a blue banner.',
```

2022-11-09 17:01 UTC, leohemsted approved these changes
one super minor test naming thing, otherwise looks really good. really like the super explicit comment in the overriden jinja template

2022-11-09 17:01 UTC, leohemsted commented on tests/templates/components/test_radios_with_hero.py
> +        "`app/templates/govuk_frontend_jinja_overrides/templates/components/radios-with-images/template.njk`"
minor stuff, think this should just be something generic just to make sure we don't forget about checkboxes either.

also this file still has "hero" in the filename. if we wanted to make it generic i'd just have `test_govuk_frontend_jinja_overrides.py` and a similar test name itself

```"any overrides found in `app/templates/govuk_frontend_jinja_overrides/`"```

2022-11-09 17:02 UTC, leohemsted commented on app/main/forms.py
> +    # this bypasses that by making self.widget a method with the same interface as widget.__call__
i've thought of a nice way to override this (basically have a `GovukFrontendField` superclass that defines the widget function, and have all the subclasses have a `govuk_frontend_component` variable that can be `text-input` or `radio-with-images` or whatever that it reads, since all these widget functions are the same.). can do that refactor separately though

2022-11-09 17:14 UTC, merged