Direct central org service users towards government identity journey
alphagov/notifications-admin pull request #4431
Opened 2022-11-04 17:41 UTC by CrystalPea

In this PR, we are direct central org service users towards government identity journey. We also make sure that back link on the Something Else page is correct.

And, as a bonus, we ensure radio buttons validation has optimum content.

Needs to go in after: https://github.com/alphagov/notifications-admin/pull/4426

### To consider:
- do we still need `.email_branding_organisation` and `.email_branding_govuk_and_org` views?
- if users select `organisation` or `govuk_and_org` as their branding choice, should we somehow take this into consideration? If not, should we even still have those options? They seem potentially confusing in the new journey.

2022-11-08 10:25 UTC, quis commented
Ideally the choice of `organisation` or `govuk_and_org` would come through in the ticket. In the first case we probably want to add it to the pool once we’ve created the branding, in the second case we need to make sure we pick ‘GOV.UK and logo’ when creating the branding

2022-11-08 17:04 UTC, CrystalPea commented
@quis 

> Ideally the choice of organisation or govuk_and_org would come through in the ticket.
Sure, I can implement this.

 In the first case we probably want to add it to the pool once we’ve created the branding
 > ok, that sounds straight forward

in the second case we need to make sure we pick ‘GOV.UK and logo’ when creating the branding
> gotcha, so best to include it as text in the ticket and maybe also as a request arg so this option gets pre-selected?

2022-11-10 16:01 UTC, quis requested changes

2022-11-10 16:01 UTC, quis commented on app/templates/support-tickets/government-logo-branding-request.txt
> +{% if branding_choice == "govuk-and-org" %}This service requested for both GOV.UK and organisation logo to be visible.
This text isn’t showing up in the ticket when I test locally, picking the _Organisation name and GOV.UK_ radio button
```suggestion
{% if branding_choice == "govuk-and-org" %}This service requested for both GOV.UK and organisation logo to be visible.
```

2022-11-10 16:32 UTC, CrystalPea commented on app/templates/support-tickets/government-logo-branding-request.txt
> +{% if branding_choice == "govuk-and-org" %}This service requested for both GOV.UK and organisation logo to be visible.
Ahh, I put in dashes instead of underscores 🤦🏼‍♀️ . Try now ☺️

2022-11-11 13:07 UTC, merged