Convert govuk button to jinja macro
alphagov/notifications-admin pull request #4435
Opened 2022-11-07 18:44 UTC by leohemsted

the last and most-used macro. A few changes to how we query for it in tests (and once in code) but otherwise relatively straightforward.

- [ ] https://github.com/alphagov/notifications-admin/pull/4429
- [ ] https://github.com/alphagov/notifications-admin/pull/4434

2022-11-08 16:11 UTC, tombye requested changes
Only a few, fairly petty requests for change. Overall looks good and I've tested across the browsers with these variants:
- buttons to submit forms sending multiple values (sign in page)
- buttons to submit forms sending single value (settings page)
- buttons to submit in-page search term (notifications page)
- buttons to upload file (add email branding page)

All looked good and worked well so, if the changes are done 👍🏻

2022-11-08 16:11 UTC, tombye commented on tests/javascripts/preventDuplicateFormSubmissions.test.js
> +    // If a form submission is caused by a input/button, this instead outputs a
This, and the other replacement in this file, would read better as:
```suggestion
    // If a form submission is caused by a submit input/button, this instead outputs a
```

Also: could we update the HTML fixture under `// set up DOM` too?

2022-11-08 16:11 UTC, tombye commented on tests/javascripts/previewPane.test.js
> +        expect(document.querySelector('form button').textContent).toEqual('Save');
Can we update the HTML fixture under `// set up DOM` so the button doesn't have the `type="submit"` any more?

2022-11-10 11:29 UTC, leohemsted reviewed
These changes seem pretty reasonable.

what i wouldn't mind, however, is [after this story] us having some thought to figure out how we can avoid swathes of HTML in our javascript and also in our test suites. Be good if we can call govuk-frontend stuff from there and not have to worry when we bump govuk that we might need to update all these things again

2022-11-10 13:57 UTC, tombye commented on app/templates/components/cookie-banner.html
> +      <button type="button" class="govuk-button notify-cookie-banner__button notify-cookie-banner__button-accept" type="button" data-accept-cookies="true" aria-describedby="notify-cookie-banner__head
Should be resolved by https://github.com/alphagov/notifications-admin/pull/4435/commits/a3f6a0f280a6ec76b8568be39c2e5ef1de323c4c

2022-11-10 13:59 UTC, tombye approved these changes
Since my last review, we found a few things that needed updating. I'm now confident all the buttons are up-to-date and using the right macro so 👍🏻

2022-11-10 15:24 UTC, samuelhwilliams approved these changes
Looks good to me 👀 👍  Nice work. All the things I spotted going commit-by-commit got resolved in later commits.

2022-11-10 16:09 UTC, merged