Platform admin set alt text
alphagov/notifications-admin pull request #4470
Opened 2022-11-25 12:49 UTC by leohemsted

| normal view | no values for either | values for both |
|-|-|-|
| <img width="367" alt="image" src="https://user-images.githubusercontent.com/5020841/203989221-3e8a6cf2-e726-498b-b861-ec54db2faf6a.png"> | <img width="495" alt="image" src="https://user-images.githubusercontent.com/5020841/203986503-5596a3ba-7d48-46d6-b063-ca799606c848.png"> | <img width="488" alt="image" src="https://user-images.githubusercontent.com/5020841/203986620-9b8fd17c-b2ce-48e0-b735-8042f0ff271e.png"> |

Text is _very_ much placeholder.

2022-11-25 12:56 UTC, samuelhwilliams commented on app/navigation.py
> +            "platform_admin_create_email_branding",
optional nit: tThese are not quite alphabetical 🙃

2022-11-25 13:02 UTC, samuelhwilliams commented on app/main/views/email_branding.py
>          brand_type=email_branding.brand_type,
We can just replace this whole block with `form = AdminEditEmailBrandingForm(obj=email_branding)`

2022-11-25 13:58 UTC, leohemsted commented on app/main/views/email_branding.py
>          brand_type=email_branding.brand_type,
niiiice. did not know that was a thing.

2022-11-25 14:11 UTC, leohemsted commented on app/navigation.py
> +            "platform_admin_create_email_branding",
yeah, was intentional cos i wanted create and update email branding next to each other :can_of_worms:

2022-11-25 14:17 UTC, quis commented on app/main/views/email_branding.py
>          brand_type=email_branding.brand_type,
<img src="https://media0.giphy.com/media/pJlJwUcgWlsuOa9ktP/giphy.webp?cid=dda24d5048282b31d3eeef9b594bda4251c14f8e17938a4d&rid=giphy.webp&ct=g">

2022-11-28 15:46 UTC, samuelhwilliams reviewed
Last commit can probably be squashed as a fixup as well

2022-11-28 15:46 UTC, samuelhwilliams commented on app/main/forms.py
> +                return False
optional nit: these can probably just be a single `if` statement; they do the same thing?

2022-11-28 15:46 UTC, samuelhwilliams commented on app/templates/views/email-branding/manage-branding.html
> +          <div style='margin-top:15px;'>{{ form.alt_text(param_extensions={'hint': {'text': 'must provide one of alt_text and text'}}) }}</div>
optional nit: we might want to change these to `govuk-!-margin-top-x` 🤔

2022-11-28 16:57 UTC, leohemsted commented on app/main/forms.py
> +                return False
changed to separate messages in https://github.com/alphagov/notifications-admin/pull/4470/commits/abcad9a639d056a3a70c740a7ebb7b05cd09fe70

2022-11-28 17:08 UTC, leohemsted commented on app/templates/views/email-branding/manage-branding.html
> +          <div style='margin-top:15px;'>{{ form.alt_text(param_extensions={'hint': {'text': 'must provide one of alt_text and text'}}) }}</div>
did some experimenting and they don't need to be in divs at all (but i added the class to the form-group div instead)

🚮

2022-11-28 17:30 UTC, leohemsted commented on app/templates/views/email-branding/manage-branding.html
> +          <div style='margin-top:15px;'>{{ form.alt_text(param_extensions={'hint': {'text': 'must provide one of alt_text and text'}}) }}</div>
[e2b531c](https://github.com/alphagov/notifications-admin/pull/4470/commits/e2b531c6e8824673c570fa058687ee6f053f2355)

2022-11-29 11:11 UTC, samuelhwilliams commented on app/main/forms.py
> +    text = GovukTextInputField("Logo Text", param_extensions={"hint": {"text": "Text that appears beside the logo"}})
Temp content or not, `Logo Text` probably doesn't need the capitalisation on the `T`. Same for alt text and the hints.

2022-11-29 11:13 UTC, leohemsted commented on app/main/forms.py
> +    text = GovukTextInputField("Logo Text", param_extensions={"hint": {"text": "Text that appears beside the logo"}})
No, I think this was intentional. CC @karlchillmaid

2022-11-29 11:14 UTC, leohemsted commented on app/main/forms.py
> +    text = GovukTextInputField("Logo Text", param_extensions={"hint": {"text": "Text that appears beside the logo"}})
This isn't temp content now, this is final. its just the service setting page stuff which karl is still playing with.

(I don't mind if karl or saima have a look just to double check capitalisation and stuff)

2022-11-29 11:17 UTC, samuelhwilliams requested changes
I've tried creating a logo from scratch and if I provide a name and logo text but no alt text, I get a 500 🤔

2022-11-29 11:17 UTC, samuelhwilliams commented on app/main/forms.py
> +                return False
I think these errors are a bit weird. We probably only want one of the fields to error in each case.

If they provide both, then add `If you enter logo text you do not need alt text` to the `alt_text` field only.
If they don't provide either, then add `You must have alt text if you do not have any logo text` to `alt_text`

2022-11-29 11:43 UTC, samuelhwilliams commented on app/main/forms.py
> +    text = GovukTextInputField("Logo Text", param_extensions={"hint": {"text": "Text that appears beside the logo"}})
oh ok. The other fields here don't have title caps? It just feels/looks inconsistent.

2022-11-29 11:58 UTC, samuelhwilliams commented on app/main/forms.py
> +                return False
Although if content/design have come up with this, then ok 👍

2022-11-29 12:12 UTC, leohemsted commented on app/main/forms.py
> +                return False
interesting thought. one of my driving thoughts behind the error messages was that you probably are thinking about logo text, and what you need to do with alt text follows from that. so maybe we assume you entered the logo text field correctly, and the alt text is the only one that shows the error?

2022-11-29 14:26 UTC, karlchillmaid commented on app/main/forms.py
> +    text = GovukTextInputField("Logo Text", param_extensions={"hint": {"text": "Text that appears beside the logo"}})
No, cap case was not intentional. I forgot to raise it on Friday because we were focused on the validation errors.

```suggestion
    text = GovukTextInputField("Logo text", param_extensions={"hint": {"text": "Text that appears beside the logo"}})
```

2022-11-29 14:27 UTC, karlchillmaid commented on app/main/forms.py
> +        "Alt Text", param_extensions={"hint": {"text": "Text for people who cannot see the logo"}}
```suggestion
        "Alt text", param_extensions={"hint": {"text": "Text for people who cannot see the logo"}}
```

2022-11-29 14:29 UTC, karlchillmaid commented on app/main/forms.py
> +                return False
I like the idea of showing only 1 error.

Current thinking:

`Cannot be empty if you do not need/enter logo text`
and
`Must be empty if you need/enter logo text`

Will give it some more thought today and confirm later.

2022-11-29 16:08 UTC, karlchillmaid commented on app/main/forms.py
> +                return False
Everyone happy with this?

`Cannot be empty if you do not have logo text`

`Must be empty if you enter logo text`

2022-11-29 16:52 UTC, samuelhwilliams commented on app/main/forms.py
> +                return False
I am 🙌  thanks!

2022-11-29 17:03 UTC, leohemsted commented on app/main/forms.py
> +                return False
fixed in 64da20b

2022-11-29 17:29 UTC, samuelhwilliams approved these changes
Nice 👍

2022-11-29 17:57 UTC, merged