Create links-and-URLs
alphagov/notifications-admin pull request #4686
Opened 2023-04-20 12:48 UTC by saimaghafoor

Adding guidance for mark down link text as a new page. 

To sit in guidance under Using Notify.

This PR needs :

- a new page 'Links and URLs'
- to be added to side navigation under Using Notify
-  to be added to the page Using notify in the bulleted list
-  the 'add links' content removed from the 'Formatting' page (edit and format)

2023-04-20 16:19 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  <p>If you have a long, complex web address, you can set up a short URL. Find out [how to set up a short URL if you have a GOV.UK domain](https://www.gov.uk/guidance/contact-the-government-digital-s
```suggestion

    <p>If you have a long, complex web address, you can set up a short URL. Find out [how to set up a short URL if you have a GOV.UK domain](https://www.gov.uk/guidance/contact-the-government-digital-service/request-a-thing#short-url).</p>
```

2023-04-20 16:20 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  <p>If you have a long, complex web address, you can set up a short URL. Find out [how to set up a short URL if you have a GOV.UK domain](https://www.gov.uk/guidance/contact-the-government-digital-s
```suggestion
  <p>If you have a long, complex web address, you may want to set up a short URL. Find out [how to set up a short URL if you have a GOV.UK domain](https://www.gov.uk/guidance/contact-the-government-digital-service/request-a-thing#short-url).</p>
```

2023-04-20 16:23 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +    <li>you can no longer control where the redirect goes</li>
Do we want to include all 3 of these? The first feels like the most compelling - but only if we explain that it might make the link seem untrustworthy.

```suggestion
    <li>your users cannot see where the link will take them</li>
    <li>your link might stop working if there’s a service outage</li>
    <li>you can no longer control where the redirect goes</li>
```

2023-04-20 16:23 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  ##Link text in emails
```suggestion
  <h2 class="heading-medium">Link text in emails</h2>
```

2023-04-20 16:29 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  ^ Apply now at https://www.gov.uk/example
```suggestion
  {{ govukInsetText({"text": "Apply now at https://www.gov.uk/example"}) }}
```

2023-04-20 16:30 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  <p>Link text may be useful if you have:</p>
```suggestion
  <p class="govuk-body">When writing an email, you can convert text into a link instead of writing the full web address.</p>
  
  <p class="govuk-body">Link text may be useful if you have:</p>
```

2023-04-20 16:31 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  <p>Never use ‘click here’, ‘click link’, ‘this link’ or ‘more’, as these do not make sense when read out of context. </p>
```suggestion
  <p class="govuk-body">Link text should tell the recipient what action they need to take and where the link goes.</p>
  
  <p class="govuk-body">Never use ‘click here’, ‘click link’, ‘this link’ or ‘more’, as these do not make sense when read out of context. </p>
```

2023-04-20 16:32 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  ##How to format link text
```suggestion
  <h3 class="heading-small">How to format link text</h3>
```

2023-04-20 16:34 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  <p>To see formatting instructions while you’re editing a template:</p>
```suggestion
  <p class="govuk-body">GOV.UK Notify uses Markdown to format link text.</p>
  <p class="govuk-body">To convert text into a link, use square brackets [] around the link text and round brackets () around the URL. Make sure there are no spaces between the brackets or the link will not work. For example:</p>
    
  {{ govukInsetText({"text": "[Apply now](https://www.gov.uk/example)"}) }}

  <p class="govuk-body">To see formatting instructions while you’re editing a template:</p>
```

2023-04-24 09:21 UTC, saimaghafoor commented on app/templates/views/guidance/using-notify/links-and-URLs
> +    <li>you can no longer control where the redirect goes</li>
I do agree the first one is the most compelling, but I also think the more we dissuade users from using short urls, the better.

2023-04-25 09:20 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +    <li>you can no longer control where the redirect goes</li>
Happy to keep it as is – we’ve no evidence that the content we’ve been using for the last few years doesn’t work 😄 

Perhaps we could add checks for URLs containing `bit.ly` and other common link shortening services to the the automated checks story?

2023-04-25 09:21 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/formatting.html
> +  <p class="govuk-body">Find <a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('NEED TO ADD LINK TO NEW LINKS AND URLS PAGE') }}"> more information on links and URls in messages</a>
```suggestion
  <p class="govuk-body">Find <a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('NEED TO ADD LINK TO NEW LINKS AND URLS PAGE') }}"> more information about links and URLs in messages</a>.</p>
```

2023-04-25 09:27 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs
> +  <p class="govuk-body">To see formatting instructions while you’re editing a template:</p>
```suggestion
  <p class="govuk-body">To see these formatting instructions while you’re editing a template:</p>
```

2023-04-26 10:44 UTC, karlchillmaid commented on app/templates/views/guidance/features/index.html
> +  <li><a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('main.guidance_links_and_URLs') }}">edit and format content</a></li>
```suggestion
  <li><a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('main.guidance_formatting') }}">edit and format content</a></li>
  <li><a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('main.guidance_links_and_URLs') }}">add links and URLs</a></li>
```

2023-04-26 10:46 UTC, karlchillmaid submitted a review, later dismissed
I think the link to the formatting page was removed in error. 

It also looks like we’ve lost the new `Links and URLs` page.

2023-04-27 09:21 UTC, leohemsted commented on app/templates/views/guidance/using-notify/links-and-URLs.html
> +  {{ govukInsetText({"text": "Apply now at https://www.gov.uk/example"}) }}
should we make this into a clickable link `<a href="https://www.gov.uk">https://www.gov.uk</a>`? just to show that they'll be automatically clickable in sms/email 🤔

2023-04-27 11:05 UTC, saimaghafoor commented on app/templates/views/guidance/using-notify/links-and-URLs.html
> +  {{ govukInsetText({"text": "Apply now at https://www.gov.uk/example"}) }}
Good point. I think here we're showing how to write link text to make it clickable. It might then be good to show an example of what it will look like when we convert it? @karlchillmaid

2023-04-27 11:13 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs.html
> +  {{ govukInsetText({"text": "Apply now at https://www.gov.uk/example"}) }}
For the sake of brevity, I don’t think we need to show the example twice.

Let’s go with Leo’s suggestion of turning the URL into a clickable link.

2023-05-02 10:16 UTC, CrystalPea approved these changes

2023-05-03 09:09 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/links-and-URLs.html
> +    href="https://www.gov.uk/guidance/contact-the-government-digital-service/request-a-thing#short-url">how to set up a short URL if you have a GOV.UK domain.</a>
```suggestion
    href="https://www.gov.uk/guidance/contact-the-government-digital-service/request-a-thing#short-url">how to set up a short URL if you have a GOV.UK domain</a>.
```

2023-05-03 09:13 UTC, karlchillmaid requested changes
I’ll approve once the suggested fixes are committed.

2023-05-04 09:18 UTC, merged