Update nested radios to govuk frontend
alphagov/notifications-admin pull request #4751
Opened 2023-06-15 10:43 UTC by BlessedDev

This PR migrates nested radio buttons to use GOVUK Frontend components. The GOVUK radio component doesn't have a nested radios solution so a nested-radio component based on the GOVUK radio component has been added.
 I have attached before and after pictures
<img width="645" alt="nested-radios-before" src="https://github.com/alphagov/notifications-admin/assets/32799090/79c6a3da-2a8b-4341-bc1b-4cbf7bd9c3c9">
<img width="619" alt="nested-radios-after-1" src="https://github.com/alphagov/notifications-admin/assets/32799090/513eb43c-053c-4f49-96ea-766774702cb3">
<img width="900" alt="nested-radios-before-2" src="https://github.com/alphagov/notifications-admin/assets/32799090/88fa134a-0715-4f49-b945-c1a5dadbac5c">
<img width="572" alt="nested-radios-after-2" src="https://github.com/alphagov/notifications-admin/assets/32799090/8d933dc3-c79c-4594-94dc-ac23d4443215">

2023-06-26 15:07 UTC, quis commented
There’s some reference to how the spacing looked when the move-to-folder radios were designed here: https://github.com/alphagov/notify-design-archive/issues/12#issuecomment-456367952

2023-07-07 16:59 UTC, BlessedDev commented
I have made quite a few changes; all radio buttons have been moved to GOVUK FE and I have also untangled radios from checkboxes. 

Before:
<img width="567" alt="nested-radios before" src="https://github.com/alphagov/notifications-admin/assets/32799090/e452e60b-57fe-42f0-9fef-522da43b8617">

After:
<img width="741" alt="nested-radios after" src="https://github.com/alphagov/notifications-admin/assets/32799090/e038f7b2-922a-4e88-a639-54933fbde9de">

2023-07-11 09:18 UTC, quis commented on app/assets/stylesheets/components/radios.scss
> +}
I think the ‘current folder’ hint looks better with a bit of space
```suggestion
.govuk-form-group--nested-radio .govuk-fieldset .govuk-radios .govuk-radios__item > .govuk-radios__hint {
  // This is intended to take 5px away from the space below a radio item
  // The enlogated selector name is to help the specificity score in order to override the margin-bottom
  // value from govuk-hint.
  margin-bottom: govuk-spacing(-1);
}
```

Before | After 
---|---
<img width="400" alt="image" src="https://github.com/alphagov/notifications-admin/assets/355079/ac7679a4-a2be-47a2-827f-4242ef8a7128"> | <img width="400" alt="image" src="https://github.com/alphagov/notifications-admin/assets/355079/600e39b2-5262-433d-a352-4b2b905bd2a2">

2023-07-11 09:22 UTC, quis commented on app/assets/stylesheets/components/radios.scss
> +  padding-left: govuk-spacing(2) + 2;
Take this away and things will align to the left edge properly
```suggestion
```

Before | After
---|---
<img width="400" alt="image" src="https://github.com/alphagov/notifications-admin/assets/355079/e662a295-899c-4401-9ee5-28c9ec5185be"> | <img width="400" alt="image" src="https://github.com/alphagov/notifications-admin/assets/355079/5a9ea265-3a6d-4367-9d88-c27c07accc7b">

2023-07-11 09:24 UTC, quis requested changes
Two small visual tweaks but otherwise think this is good to go now

2023-07-17 09:09 UTC, quis approved these changes

2023-07-17 09:15 UTC, merged