Viewing an attachment on the manage-attachment page
alphagov/notifications-admin pull request #4767
Opened 2023-06-30 14:00 UTC by whpearson

This simply adds the looping logic to the manage-attachment page

We may want to pull it out to it's own template so it can be reused for the validation failure page.

Added a simple test for the endpoint

goes with https://github.com/alphagov/notifications-template-preview/pull/739

2023-07-10 11:02 UTC, quis requested changes

2023-07-10 11:02 UTC, quis commented on app/templates/views/templates/manage-attachment.html
> +          <div class="letter page--{{ loop.cycle('odd', 'even') }}{% if loop.first %} page--first{% endif %}{% if loop.last %} page--last{% endif %}">
Think this would be better wrapped up in a class, but happy to save that for a subsequent refactor.

Technically whether the first page of the attachment is `page--odd` or `page--even` depends on how many pages are in the template. This would be easier to do after a refactor though, so doesn’t need to change now.

2023-07-10 11:02 UTC, quis commented on tests/app/main/views/test_templates.py
> +
Should probably add a test for:
- correct number of images are shown on the page
- at least the first image has the correct `src` attribute

2023-07-10 14:19 UTC, whpearson commented on app/templates/views/templates/manage-attachment.html
> +          <div class="letter page--{{ loop.cycle('odd', 'even') }}{% if loop.first %} page--first{% endif %}{% if loop.last %} page--last{% endif %}">
But we aren't showing the rest of the template here, does that matter?

2023-07-10 14:36 UTC, whpearson commented on app/templates/views/templates/manage-attachment.html
> +          <div class="letter page--{{ loop.cycle('odd', 'even') }}{% if loop.first %} page--first{% endif %}{% if loop.last %} page--last{% endif %}">
Yeah I think saving it for a refactor makes sense.

2023-07-11 09:11 UTC, quis approved these changes

2023-07-11 12:07 UTC, merged