Enable error summaries for service settings pages
alphagov/notifications-admin pull request #4831
Opened 2023-09-15 10:53 UTC by BlessedDev

This PR enables error summaries for the admin app service settings pages as specified in [this](https://trello.com/c/8JBMz4Nu/459-add-error-summaries-to-service-settings-page-forms) ticket.

I have attached pictures depicting the changes:

2023-09-15 12:16 UTC, karlchillmaid commented on tests/app/main/views/service_settings/test_service_settings.py
> +        ("url", "invalid.com/", "Enter a URL in the correct"),
```suggestion
        ("url", "invalid.com/", "Enter a URL in the correct format"),
```

2023-09-15 12:17 UTC, karlchillmaid commented on tests/app/main/views/test_providers.py
> +        ({"sms_provider_1": 99.9, "sms_provider_2": 0.1}, "Enter percentage in digits"),
```suggestion
        ({"sms_provider_1": 99.9, "sms_provider_2": 0.1}, "Enter a percentage in digits"),
```

2023-09-15 12:18 UTC, karlchillmaid commented on tests/app/main/views/test_providers.py
> +        ({"sms_provider_1": 99.9, "sms_provider_2": 0.1}, "Enter percentage in digits"),
Sam and I discussed this interaction and whether we could improve it.

For example, changing the design to up/down buttons that remove the need for users to enter 2 percentages that balance.

2023-09-15 12:22 UTC, karlchillmaid requested changes
I’ve left a couple of small changes - hopefully they’re just things that got missed when updating the tests, but worth checking back against the errors themselves.

Apart from that, as far as I can tell without seeing everything in context, the content looks good. We discussed adding screenshots for every error, but it’s a lot of effort.

2023-09-15 13:18 UTC, BlessedDev commented on tests/app/main/views/test_providers.py
> +        ({"sms_provider_1": 99.9, "sms_provider_2": 0.1}, "Enter percentage in digits"),
@karlchillmaid  I have corrected the errors you highlighted

2023-09-15 13:31 UTC, karlchillmaid approved these changes
Can’t see any errors in the content.

2023-09-19 06:54 UTC, samuelhwilliams commented
I think we can also update `service_edit_email_reply_to` to include error summaries 👍

2023-09-19 08:19 UTC, BlessedDev commented
> This ticket talks about adding error summaries to "service settings pages". I've noticed quite a few pages under service settings that don't have error summaries enabled still after this PR. Have they been missed here, or are they part of some other ticket? If not the latter then I think we should try to cover off all of the service settings pages here.
> 
> Some missing pages:
> 
> * `service_edit_email_reply_to`
> * `email_branding_options`
> * `service_edit_sms_sender`
> * `service_edit_letter_contact`
> * `letter_branding_options`

I followed the ticket's specifications and they weren't covered in the ticket. I am not sure they are covered in other tickets. I do see your point about covering as much as possible rather than racking up work for later. I will address those pages as part of this PR.

2023-09-19 11:36 UTC, BlessedDev commented on app/main/forms.py
> +                raise StopValidation(f"Enter {self.things} in digits")
Agreed

2023-10-06 07:31 UTC, samuelhwilliams commented
The "Data retention" (platform admin) service settings edit page don't have an error summary on them either, I've just noticed.

<img width="994" alt="image" src="https://github.com/alphagov/notifications-admin/assets/2920760/7c2bca1a-0b72-4bfa-a6f8-5b6153082d5d">

Also the backlink on those pages is broken, if you want to fix that now go ahead - otherwise I'll try to remember to do it separately :)

2023-10-06 07:44 UTC, BlessedDev commented
> The "Data retention" (platform admin) service settings edit page don't have an error summary on them either, I've just noticed.
> 
> <img alt="image" width="994" src="https://user-images.githubusercontent.com/2920760/273136490-7c2bca1a-0b72-4bfa-a6f8-5b6153082d5d.png">
> Also the backlink on those pages is broken, if you want to fix that now go ahead - otherwise I'll try to remember to do it separately :)
> 
> Everything else here looks as expected so will be happy to 👍 ✅ this afterwards

Good catch. I will add a fix for both issues.

2023-10-06 08:04 UTC, tombye reviewed
The code looks good to me except the comment I added and one thing I noticed that didn't seem right in how the validation for reply-to email addresses.

I used an existing reply-to email and saw this error: 'Enter an email address in the correct format, like name@example.gov.uk' when I was expecting one about using an existing address. I know it was in the right format because it was an existing address.

Other than that, it all looks great and is a ton of work so thanks for doing it all!

2023-10-06 08:40 UTC, tombye commented on app/main/forms.py
> +            self.url.validators = [
I meant to comment on this as part of my review (sorry to do it now instead). It seems odd to message with 'a URL in the correct format' for an 'input is required' error. I checked and this does match the spreadsheet so we should confirm with @karlchillmaid what the expected content is but it seems out of sync with how we do that type of error elsewhere here.

2023-10-06 09:41 UTC, BlessedDev commented
@samuelhwilliams I have pushed a fix for the broken back page link.

2023-10-06 10:06 UTC, samuelhwilliams commented on app/main/forms.py
> +        validators=[validators.NumberRange(min=3, max=90, message="The number of days must be between 3 and 90")],
We can also update the `AdminServiceEditDataRetentionForm` form below which is used on these pages too (or, well, editing an existing data retention as opposed to just creating one) :)

2023-10-06 10:33 UTC, karlchillmaid commented on app/main/forms.py
> +                NotifyDataRequired(thing="a URL in the correct format"),
```suggestion
                NotifyDataRequired(thing="a URL"),
```

2023-10-06 10:34 UTC, karlchillmaid commented on app/main/forms.py
> +                NotifyUrlValidator(),
We need this validation error if the URL is not valid:

```suggestion
                NotifyUrlValidator(thing="a URL in the correct format"),
```

2023-10-06 10:37 UTC, samuelhwilliams commented on app/main/forms.py
> +                NotifyUrlValidator(),
That fragment is the default if none is provided, so it's best left blank here 👍

2023-10-06 10:43 UTC, karlchillmaid commented on app/main/forms.py
> +            self.url.validators = [
@BlessedDev I’ve paired with Tom to correct the mistake I made in the spreadsheet for these 2 errors.

There’s another change described in the spreadsheet, which I’ll add here for clarity:

1. "Rename the form field `Link to a website`
2. Add hint text to the form field`For example, https://www.example.gov.uk`

2023-10-06 14:20 UTC, BlessedDev commented on app/main/forms.py
> +                NotifyUrlValidator(),
@samuelhwilliams is right that it is the default error message and should doesn't need to be explicitly stated.

2023-10-09 09:52 UTC, karlchillmaid commented on app/main/forms.py
> +                NotifyUrlValidator(),
Sorry. Tom and I thought that this was the validation for a badly formatted URL.

2023-10-09 11:15 UTC, BlessedDev commented on app/main/forms.py
> +            self.url.validators = [
> @BlessedDev I’ve paired with Tom to correct the mistake I made in the spreadsheet for these 2 errors.
> 
> There’s another change described in the spreadsheet, which I’ll add here for clarity:
> 
> 1. "Rename the form field `Link to a website`
> 2. Add hint text to the form field `For example, https://www.example.gov.uk`

These are great changes and I have implemented them. It is definitely much more user friendly.

![Screenshot 2023-10-09 at 11 43 42](https://github.com/alphagov/notifications-admin/assets/32799090/7696d29b-5ced-45b1-9832-c733c319d245)

2023-10-09 12:58 UTC, samuelhwilliams commented
This page still needs error summaries enabled

<img width="1002" alt="image" src="https://github.com/alphagov/notifications-admin/assets/2920760/357bdd31-3212-44b5-a175-0264c4aa73ba">

2023-10-10 13:01 UTC, samuelhwilliams approved these changes

2023-10-10 15:26 UTC, merged