Make organisation add page consistent with other platform admin pages
alphagov/notifications-admin pull request #4858
Opened 2023-10-13 12:27 UTC by BlessedDev

Currently the organisations/add page has a layout that is not consistent with other platform admin pages and especially not consistent with the organisations page that links to it. 
Enabling error summaries introduced aesthetic issues that are resolved by making the page consistent with the patterns established in the other platform admin pages.

This PR updates `organisations/add-organisation.html` and enables error summaries for `/organisations/add` route. 

Before:
<img width="1015" alt="before-1" src="https://github.com/alphagov/notifications-admin/assets/32799090/754b9808-a532-4323-ad2e-16e6bd17dbe2">

2023-10-13 13:07 UTC, samuelhwilliams reviewed
It looks like you're also tackling the error messages for this page at the same time. Not sure if you kicked this off with Karl to loop him in on the error messages beforehand?

I had a quick look at the error messages for this page from the audit doc, and it looks like the new error message when adding an organisation with a name that already exists should be "This organisation name is already in use - contact GOV.UK Notify support". Think we still need to update that here.

All the other error messages look good to me.

2023-10-13 13:07 UTC, samuelhwilliams commented on app/templates/views/organisations/add-organisation.html
> +    <div class="govuk-grid-column-full">
I think these divs are redundant now as well - at least, removing them provides no obvious visual change. A number of other platform admin pages don't have them (but I admit some do, so it seems slightly inconsistent).

Probably fine to remove :)

2023-10-13 13:57 UTC, BlessedDev commented
> Good spot on the page layout here and nice work being proactive on fixing it 👍
> 
> It looks like you're also tackling the error messages for this page at the same time. Not sure if you kicked this off with Karl to loop him in on the error messages beforehand?
> 
> I had a quick look at the error messages for this page from the audit doc, and it looks like the new error message when adding an organisation with a name that already exists should be "This organisation name is already in use - contact GOV.UK Notify support". Think we still need to update that here.
> 
> All the other error messages look good to me.

Thanks for spotting that, I missed that error message.

2023-10-13 14:42 UTC, BlessedDev commented on app/main/views/organisations/index.py
> +                form.name.errors.append("This organisation name is already in use - contact GOV.UK Notify support")
> @karlchillmaid should this be a hyperlink to the support page?

I can see the value of making it a hyperlink as it would make life easier for our users. However If we are to go down that route, given that the error summary messages are displayed as links already, wouldn't it mean using a flash message instead?

2023-10-13 14:47 UTC, samuelhwilliams commented on app/main/views/organisations/index.py
> +                form.name.errors.append("This organisation name is already in use - contact GOV.UK Notify support")
We can make the part of the error message that displays next to the input a link, but in the error summary that would need to get stripped out yeah.

We do something similar here:

<img width="654" alt="image" src="https://github.com/alphagov/notifications-admin/assets/2920760/7c27743b-fafe-4715-9f6c-f12bfb4c74b3">

2023-10-13 14:49 UTC, BlessedDev commented on app/main/views/organisations/index.py
> +                form.name.errors.append("This organisation name is already in use - contact GOV.UK Notify support")
Thanks, that is a good example. I favour the error summaries to flash messages were feasible.

2023-10-13 16:47 UTC, klssmith commented on app/main/views/organisations/index.py
> +                form.name.errors.append("This organisation name is already in use - contact GOV.UK Notify support")
The form only gets used for platform admin users - just out of curiosity, is that going to change if the error message is changing to link to contact support?

2023-10-13 17:22 UTC, BlessedDev commented on app/main/views/organisations/index.py
> +                form.name.errors.append("This organisation name is already in use - contact GOV.UK Notify support")
> The form only gets used for platform admin users - just out of curiosity, is that going to change if the error message is changing to link to contact support?

You're right, it is only seen by platform admins. So the part about contacting support should be dropped.

2023-10-16 09:39 UTC, quis requested changes
Everything else looks good so just need to resolve the error message content

2023-10-16 09:39 UTC, quis commented on app/main/views/organisations/index.py
> +                form.name.errors.append("This organisation name is already in use - contact GOV.UK Notify support")
Agree that we don’t need the part about contacting support 
```suggestion
                form.name.errors.append("This organisation name is already in use")
```

2023-10-16 10:01 UTC, BlessedDev commented on app/main/views/organisations/index.py
> +                form.name.errors.append("This organisation name is already in use - contact GOV.UK Notify support")
I have removed the section of the message that refers to contacting support.

2023-10-16 10:09 UTC, quis approved these changes

2023-10-16 10:12 UTC, merged