Add archive_service_confirmation_message.html
alphagov/notifications-admin pull request #4894
Opened 2023-11-14 15:12 UTC by BlessedDev

This PR updates `archive_service` to add guidance to the confirmation message shown to  platform_admins while archiving a service. The details are described [here](https://trello.com/c/KHKQOYfT/462-add-guidance-to-the-confirmation-message-shown-when-you-archive-a-service).

platform_admin confirmation message:
![Screenshot 2023-11-14 at 13 08 46](https://github.com/alphagov/notifications-admin/assets/32799090/df578217-3be4-42b6-8df4-026d0633ea9d)

user confirmation message
![Screenshot 2023-11-14 at 13 07 58](https://github.com/alphagov/notifications-admin/assets/32799090/b49c3df6-4560-4cb4-b688-2d5c1431d136)

2023-11-14 16:47 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +             <li>is aware they will no longer be able to use the inbound number to receive replies if there is one</li>
Can we make this line conditional, so we only show it if the service has ‘Receive text messages’ enabled?

2023-11-14 16:48 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +      <h3 class="govuk-body govuk-!-font-weight-bold">Before you delete ‘{{service_name}}’, confirm the user: </h3>
```suggestion
      <h3 class="govuk-body govuk-!-font-weight-bold">Before you delete ‘{{service_name}}’, confirm:</h3>
```

2023-11-14 16:51 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
```suggestion
      <h3 class="govuk-body govuk-!-font-weight-bold">You also need to:</h3>
           <ul class="govuk-list govuk-list--bullet">
              <li>check the user has the ‘Manage settings, team and usage’ permission for this service</li>
              <li>ask a team member with the ‘Manage settings, team and usage’ permission to confirm the request</li>
              <li>check if the service has exceeded its annual allowance, in case we need to raise an invoice</li>
           </ul>
```

The main change here is combining bullets 1 and 2 into a single instruction.

My other suggestions are minor edits to make the language shorter and more active.

2023-11-14 17:41 UTC, BlessedDev commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +             <li>has given the exact name of the service they want to delete</li>
@karlchillmaid Did you mean `<li>has given the exact name of the service the user wants to delete</li>`?

2023-11-14 17:44 UTC, BlessedDev commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
Thanks @karlchillmaid. Combining the first two bullet points makes sense.

2023-11-14 18:21 UTC, BlessedDev commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +             <li>is aware they will no longer be able to use the inbound number to receive replies if there is one</li>
It is possible, but since it can be quickly checked on the service settings page and it is a feature for platform admins only, I don't think it is necessary to add extra logic to deal with it.

2023-11-15 09:23 UTC, saimaghafoor commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +             <li>is aware they will no longer be able to use the inbound number to receive replies if there is one</li>
Happy for it to remain as is. We could test/monitor how useful platform admins find the guidance which could then inform of any changes needed.

2023-11-15 09:47 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +             <li>has given the exact name of the service they want to delete</li>
No, because we’ve removed ‘the user’ from the lead-in line.

So it now reads:

> Before you delete ‘service name’, confirm:
>
>* the exact name of the service the user wants to delete

My hope is that ‘confirm the exact name’ makes it clear (implicitly) that you need to check this with the user.

2023-11-15 09:51 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +             <li>is aware they will no longer be able to use the inbound number to receive replies if there is one</li>
That approach makes sense.

In which case, this line should probably change a bit to fit with the new lead-in line.

Something like:

```suggestion
             <li>the user understands they can no longer receive text messages (if they use this feature)</li>
```

2023-11-15 09:55 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
@BlessedDev Do we still need to commit this suggestion?

2023-11-15 09:57 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +                  to raise an invoice for </li>
```suggestion
      <h3 class="govuk-body govuk-!-font-weight-bold">You also need to:</h3>
           <ul class="govuk-list govuk-list--bullet">
              <li>check the user has the ‘Manage settings, team and usage’ permission for this service</li>
              <li>ask a team member with the ‘Manage settings, team and usage’ permission to confirm the request</li>
              <li>check if the service has exceeded its annual allowance, in case we need to raise an invoice</li>
```

2023-11-15 10:00 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
I’ve made a new commit to update this.

2023-11-15 10:27 UTC, saimaghafoor commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
Thanks Karl. not sure how to accept suggestions for that?

2023-11-15 12:20 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
I was thinking about other ways to structure these instructions.

There’s a lot the user needs to think about/do, and probably an order of priority in which to do it.

### Version 1


>Before you delete this service:
>
>1. Confirm the exact name of the service the user wants to delete.
>1. Check the user has the ‘Manage settings, team and usage’ permission for this service.
>
> If the service can receive text messages, tell the user that their phone number will stop working.
>
> Do not delete the service until you have:
>
>* confirmation from another team member with the ‘Manage settings, team and usage’ permission
>* checked if we need to raise an invoice

### Version 2
This one condenses all the most important stuff into a numbered list, rather than 2 lists of competing priority.

>Before you delete this service:
>
>1. Confirm the exact name of the service the user wants to delete.
>1. Check the user has the ‘Manage settings, team and usage’ permission for this service.
>1. Confirm the request with another team member who has the ‘Manage settings, team and usage’ permission.
>1. Check if we need to raise an invoice.
>
>If the service can receive text messages, tell the user that their phone number will stop working.

2023-11-15 13:06 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
After discussing with Saima on Slack, we’re suggesting this for our MVP.

We need to monitor this over time and check in with the team to understand if we want to:

* add more content
* remove anything
* reintroduce the nuance of Saima’s original 2 list approach
* revisit the idea of taking users to a separate page

```suggestion
      <h3 class="govuk-body govuk-!-font-weight-bold">Before you delete ‘{{service_name}}’: </h3>
           <ol class="govuk-list govuk-list--number">
             <li>Confirm the exact name of the service the user wants to delete.</li>
             <li>Check the user has the ‘Manage settings, team and usage’ permission for this service.</li>
             <li>Confirm the request with another team member who has the ‘Manage settings, team and usage’ permission.</li> 
             <li>Check if we need to raise an invoice.</li>           
           </ol>
           
       <p class="govuk-body">If the service can receive text messages, tell the user that their phone number will stop working.</p>
```

2023-11-15 13:12 UTC, saimaghafoor commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ul>
Happy with the succinctness of the content and, once in use,  would like feedback from the team on how well the guidance is/isn't working.

2023-11-16 11:25 UTC, BlessedDev commented on tests/app/main/views/service_settings/test_service_settings.py
> +platform_admin_archive_service_confirmation_message = """
I take your point. I have gone for the option of the test being less prescriptive as the content is still subject to future change.
The content for both users and platform admins will always have the text: "Are you sure you want to delete", so I have adjusted the test to check for this rather than check that that guidance has been added as in the case of platform admins.

2023-11-16 12:09 UTC, tombye requested changes
Just one change I think needed, otherwise happy to approve once that's dealt with.

2023-11-16 12:11 UTC, tombye commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +      <h3 class="govuk-body">Before you delete ‘{{service_name}}’: </h3>
I think this can just be a paragraph as there is already a convention with the leading paragraph before a list being a kind of label for the points.

```suggestion
      <p class="govuk-body">Before you delete ‘{{service_name}}’: </p>
```

2023-11-16 13:51 UTC, tombye approved these changes
I know there's still 1 comment left to be resolved but everything else (including the suggestion I raised) looks good to me 👍🏻

2023-11-16 15:56 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +      <p class="govuk-body">Before you delete ‘{{service_name}}’: </p>
```suggestion
      <p class="govuk-body">Before you delete this service: </p>
```

2023-11-16 15:57 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +           </ol>
```suggestion
           <ul class="govuk-list govuk-list--bullet">
             <li>confirm the exact name of the service the user wants to delete</li>
             <li>check the user has the ‘Manage settings, team and usage’ permission for this service</li>
             <li>confirm the request with another team member who has the ‘Manage settings, team and usage’ permission</li>
             <li>check if we need to raise an invoice</li>
           </ul>
```

2023-11-16 15:57 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +       <p class="govuk-body">If the service can receive text messages, tell the user that their phone number will stop working.</p>
```suggestion
       <p class="govuk-body">If the service can receive text messages, tell the user that the phone number for this service will stop working.</p>
```

2023-11-16 16:24 UTC, BlessedDev commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +      <p class="govuk-body">Before you delete ‘{{service_name}}’: </p>
@karlchillmaid 
I think there is some value to explicitly stating the name of the service in case the wrong service is about to be archived.

2023-11-16 16:41 UTC, karlchillmaid commented on app/templates/partials/flash_messages/archive_service_confirmation_message.html
> +      <p class="govuk-body">Before you delete ‘{{service_name}}’: </p>
I agree, but we already show the service name in the heading directly above this line.

2023-11-17 10:30 UTC, merged