Update roadmap
alphagov/notifications-admin pull request #4999
Opened 2024-02-22 21:51 UTC by karlchillmaid

This pull request updates the roadmap page to reflect:

* what we’re working on now
* what we’re doing next
* what we’ve done

2024-02-22 21:53 UTC, karlchillmaid commented on app/templates/views/guidance/features/roadmap.html
> +    <li>Launch RCS messaging</li>
```suggestion
    <li>Launch RCS messaging (<a class="govuk-link govuk-link--no-visited-state" href="https://www.gov.uk/service-manual/agile-delivery/how-the-alpha-phase-works">alpha</a>)</li>
```

2024-02-23 10:12 UTC, tombye requested changes
The code looks code and renders fine in a browser and also the links all work. I just have one comment but otherwise this looks good 👍🏻

2024-02-23 10:12 UTC, tombye commented on app/templates/views/guidance/features/roadmap.html
> -    <li>Update the Service Manual guidance about <a class="govuk-link govuk-link--no-visited-state" href="https://www.gov.uk/service-manual/design/sending-emails-and-text-messages">planning and writi
Can we please change this link so it wraps around the 'the Service Manual guidance about planning and writing emails and text messages' text instead?

2024-02-23 10:20 UTC, karlchillmaid commented on app/templates/views/guidance/features/roadmap.html
> -    <li>Update the Service Manual guidance about <a class="govuk-link govuk-link--no-visited-state" href="https://www.gov.uk/service-manual/design/sending-emails-and-text-messages">planning and writi
We’re removing this line anyway, so the link won’t be part of the updated page.

2024-02-23 10:24 UTC, tombye commented on app/templates/views/guidance/features/roadmap.html
> -    <li>Update the Service Manual guidance about <a class="govuk-link govuk-link--no-visited-state" href="https://www.gov.uk/service-manual/design/sending-emails-and-text-messages">planning and writi
🤦🏻

2024-02-23 10:24 UTC, tombye approved these changes
I only had one change requested and it was wrong 🤦🏻, so 👍🏻

2024-02-23 10:37 UTC, merged