Convert cookie banner to use design system component
alphagov/notifications-admin pull request #5039
Opened 2024-04-12 12:21 UTC by kr8n3r

2024-04-19 14:24 UTC, tombye requested changes
This is great and nice to see us now able to delete more custom code.

Only change I think is needed is to move the remaining CSS in `app/assets/stylesheets/components/cookie-message.scss` to `app/assets/stylesheets/govuk-frontend/overrides.scss` to put it with the others.

2024-04-19 14:24 UTC, tombye commented on app/assets/javascripts/cookieMessage.js
> +    target.focus();
This is much better moved to here 👍🏻.

2024-04-19 14:50 UTC, kr8n3r commented
> This is great and nice to see us now able to delete more custom code.
> 
> Only change I think is needed is to move the remaining CSS in `app/assets/stylesheets/components/cookie-message.scss` to `app/assets/stylesheets/govuk-frontend/overrides.scss` to put it with the others.

done

2024-04-19 14:58 UTC, tombye approved these changes
Looks perfect now 👍🏻

2024-04-22 10:14 UTC, idavidmcdonald approved these changes
Nice, I've reviewed the 2 commits since Tom's latest approval and they look all fine to me (especially given the tests are passing). I'm not an expert on this stuff but given that, I think I'm Ok to approve.

2024-04-22 13:02 UTC, merged