Enable error summary for platform admin letter branding edit
alphagov/notifications-admin pull request #5060
Opened 2024-04-26 15:59 UTC by idavidmcdonald

https://trello.com/c/Uu9YoBkj/710-make-forms-for-uploading-files-meet-validation-requirements

This is the first page to be fixed for that trello ticket. On an error with the file upload, it:

- adds ‘Error: ’ to the beginning of the page <title> so screen readers read it out as soon as possible
- shows an error summary at the top of the page, and move keyboard focus to it
- shows error messages next to fields with errors

I'm less sure on the criteria 'show them the page again, with the form fields as the user filled them in' as we don't show them the bad logo they uploaded. Should we be?

I used my initiative to change the error message to something more consistent and less informal. I copied the pattern from the form below which we show to our users which uses 'Branding must be an SVG file'. It may not be perfect, but I think it is a bit better than what we had before.

## Before

<img width="1790" alt="image" src="https://github.com/alphagov/notifications-admin/assets/7228605/d5f32089-5778-4098-9572-6a63b2612a14">

## After

<img width="1789" alt="image" src="https://github.com/alphagov/notifications-admin/assets/7228605/f09cc2ee-bec2-421f-aa7f-e0a2ed951f3f">

2024-04-26 16:25 UTC, kr8n3r commented
I wouldn't expect us to show them the "bad logo" or wrong format if they try to hack the `accept` attribute. 

With regards to `show them the page again, with the form fields as the user filled them in`: 
if the users first updates the brand name and then tries to hackily submit a non-svg file, on page refresh, the brand name reverts back to the original text.

I think in this particular form scenarios it's not too big of a deal

2024-05-15 12:55 UTC, idavidmcdonald commented
I've checked the other branding routes and I believe they already meet the accessibility criteria. Here are screenshots of the remaining 3 (the letter branding edit route is screenshotted in the original PR)

## /letter-branding/create

![image](https://github.com/alphagov/notifications-admin/assets/7228605/bc48d2bc-940c-4777-a952-bd892b4e979c)

## /email-branding/<branding-id>/edit

![image](https://github.com/alphagov/notifications-admin/assets/7228605/9d6c0193-da43-4c25-a968-3bcbb6e27fee)

## /email-branding/create

![image](https://github.com/alphagov/notifications-admin/assets/7228605/7dfe5124-6c1b-4b65-9489-e0714654bf22)

2024-05-16 08:56 UTC, tombye requested changes
There are a few, tiny, changes I've suggested in comments to make the validation messages match the spreadsheet but once those are addressed this is good to go 👍🏻 

Note: we had a discussion about this work outside of this PR and decided the validation for uploading a contact list or letter is out of scope for this PR and will be split off into its own card.

2024-05-16 08:56 UTC, tombye commented on app/main/forms.py
> +    file = VirusScannedFileField("Upload a PNG logo", validators=[FileAllowed(["png"], "Logo must be a PNG file")])
```suggestion
    file = VirusScannedFileField("Upload a PNG logo", validators=[FileAllowed(["png"], "The logo must be a PNG file")])
```

To match the content in row 100 of [the validation audit spreadsheet](https://docs.google.com/spreadsheets/d/1yeBQnz_M48W4QebzHp2Uq-M_D0u9hnXfjQGuRpJwYf8/edit?usp=sharing)

2024-05-16 08:56 UTC, tombye commented on app/main/forms.py
> +            FileAllowed(["svg"], "Logo must be an SVG file"),
```suggestion
            FileAllowed(["svg"], "the logo must be an SVG file"),
```

This doesn't seem to be in the validation audit spreadsheet but this change would make it consistent with the email one.

2024-05-16 08:56 UTC, tombye commented on tests/app/main/views/test_letter_branding.py
> +    assert page.select_one(".error-message").text.strip() == "Logo must be an SVG file"
```suggestion
    assert page.select_one(".error-message").text.strip() == "The logo must be an SVG file"
```

2024-05-16 08:56 UTC, tombye commented on tests/app/main/views/test_letter_branding.py
> +    assert page.select_one(".error-message").text.strip() == "Logo must be an SVG file"
```suggestion
    assert page.select_one(".error-message").text.strip() == "The logo must be an SVG file"
```

2024-05-16 08:56 UTC, tombye commented on tests/javascripts/fileUpload.test.js
> +    uploadLabel.innerHTML += '<span class="error-message">Logo must be a PNG file</span>';
```suggestion
    uploadLabel.innerHTML += '<span class="error-message">The logo must be a PNG file</span>';
```

For consistency with the other instances of this field.

2024-05-16 08:56 UTC, tombye commented on tests/javascripts/fileUpload.test.js
> +    expect(buttonLabel.textContent.trim().replace(/\s{2,}/g, ' ')).toEqual("Upload logo Logo must be a PNG file");
```suggestion
    expect(buttonLabel.textContent.trim().replace(/\s{2,}/g, ' ')).toEqual("Upload logo The logo must be a PNG file");
```

2024-05-17 09:45 UTC, merged