Change all multi-line textboxes to use the GOV.UK Frontend textarea component
alphagov/notifications-admin pull request #5073
Opened 2024-05-09 11:09 UTC by kr8n3r

2024-05-14 11:35 UTC, tombye requested changes
This all looks good to me and only a few comments. Happy to approve once they've been looked at.

2024-05-14 11:35 UTC, tombye commented on app/main/forms.py
> +    def get_error_message(self, error_message_format="text"):
Think this is inherited from `GovukFrontendWidgetMixin` so doesn't need defining again.

2024-05-14 11:43 UTC, kr8n3r commented on app/assets/javascripts/enhancedTextbox.js
> +        Boolean(textarea.data('autofocusTextbox')) ||
sure

2024-05-14 11:43 UTC, kr8n3r commented on tests/javascripts/enhancedTextbox.test.js
> +      test("If the textbox is a <textarea>", () => {
yep can do

2024-05-16 08:36 UTC, tombye approved these changes
Thanks for addressing the comments. All looking good now so 👍🏻 

Massive piece of work too, congrats!

2024-05-16 09:24 UTC, merged