WIP Change headless tables to summary list component
alphagov/notifications-admin pull request #5078
Opened 2024-05-14 10:25 UTC by kr8n3r

2024-05-15 14:59 UTC, kr8n3r commented
> Can you make sure that the widths of the columns still match the grid in #2931 please and thanks

certainly 
<img width="957" alt="Screenshot 2024-05-15 at 15 59 34" src="https://github.com/alphagov/notifications-admin/assets/3758555/df4ace14-49df-4ecd-93a7-b89102fefa2e">

2024-05-22 16:23 UTC, tombye requested changes
I spotted a few things that I've added comments about.

I think the `<dt>` needs to be `35%` including padding, based on [Chris's previous work on the settings pages](https://github.com/alphagov/notifications-admin/pull/2931/files) so we'll have to introduce a new class like `notify-summary-list__key--one-quarter`.

If all that can be sorted, this should be good to go. 👏🏻 👏🏻 for doing such a large piece of work that'll tick off a need that keeps coming up in accessibility audits 🏅.

2024-05-23 08:34 UTC, kr8n3r commented on app/templates/views/service-settings.html
> +      {% set email_settings_rows = base_email_settings_row + restricted_email_settings_rows  if restricted_email_settings_rows else base_email_settings_row %}
sorted

2024-05-23 08:36 UTC, kr8n3r commented on app/templates/views/service-settings.html
> +      {% set base_etter_settings_row = [
sorted, and fixed an additional one as well. I had camelCase before so had to rename them all

2024-05-23 08:45 UTC, kr8n3r commented
> I think the `<dt>` needs to be `35%` including padding, based on [Chris's previous work on the settings pages](https://github.com/alphagov/notifications-admin/pull/2931/files) so we'll have to introduce a new class like `notify-summary-list__key--one-quarter`.
> 

yeah, i think i was reading the table layout wrongly as I saw 2/8

2024-05-23 09:06 UTC, kr8n3r commented
I have also applied the key width class to the /user-settings table as well

2024-05-23 10:41 UTC, tombye approved these changes
Thanks for making the changes, and plugging them into the user profile page.

This looks good to go now 👍🏻

2024-05-23 13:57 UTC, merged