Update unsubscribe-links.html
alphagov/notifications-admin pull request #5092
Opened 2024-05-21 13:20 UTC by saimaghafoor

New content  added for 'one-click unsubscribe link in the header of an email'.  Signpost users to API documentation for more information.

Removed reference to google and yahoo

Story: https://trello.com/c/WoTzSW56

2024-05-22 08:27 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +  <p class="govuk-body">If recipients report your emails as spam we can stop you from using GOV.UK Notify.</p>
```suggestion
  <p class="govuk-body">You must let recipients opt out of subscription emails.</p>
  <p class="govuk-body">If you do not, they can report your emails as spam. If this happens we may stop you from using GOV.UK Notify.</p>
  <p class="govuk-body">Transactional emails do not need to include an unsubscribe link.</p>

```

2024-05-22 08:27 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +  </ol>
```suggestion
  <p class="govuk-body">There are 2 ways to let recipients opt out</p>
  <ol class="govuk-list govuk-list--number">
    <li>Add an unsubscribe link to the body of your email</li>
    <li>Add a one-click unsubscribe button to the email header.</li>
  </ol>
```

2024-05-22 08:29 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
>    <p class="govuk-body">The GOV.​UK Service Manual explains the difference between <a class="govuk-link govuk-link--no-visited-state"
This line feels like it belongs with ‘Transactional emails do not need to include an unsubscribe link.’ – but it also feels less important than the 2 bullet points.

If you can ask a dev to attach screenshots to the PR, seeing how the page will look might help with the final decision.

2024-05-22 08:31 UTC, saimaghafoor commented
@BlessedDev could we have a preview of the content please if possible?

2024-05-22 08:33 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +  <p class="govuk-body">You must let recipients opt out of subscription emails.</p>
```suggestion
  <p class="govuk-body">You must let people opt out of receiving subscription emails.</p>
```

Just putting this in as something to consider. It feels right to qualify what we mean by ‘opt out’, but we probably don’t want recipients and receiving together in the same sentence.

2024-05-22 08:35 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
>    <p class="govuk-body">The GOV.​UK Service Manual explains the difference between <a class="govuk-link govuk-link--no-visited-state"
The more I re-read this, the more I think ‘move it above the bullets’... 🤔

2024-05-22 10:27 UTC, saimaghafoor commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
>    <p class="govuk-body">The GOV.​UK Service Manual explains the difference between <a class="govuk-link govuk-link--no-visited-state"
Yes i think it sits better above the bullets when we're referencing subscription/transactional emails

2024-05-22 11:49 UTC, karlchillmaid commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +  <p class="govuk-body">There are 2 ways to let recipients opt out</p>
```suggestion
  <p class="govuk-body">There are 2 ways to let recipients opt out:</p>
```

2024-05-23 10:49 UTC, BlessedDev requested changes
Well done on the content, it is very succinct. There is a lot of to be worked out regarding unsubscribe links and I think we should say as little as possible while giving as much helpful information as possible, and this PR lays a solid foundation and strikes the right balance. 
I have asked for a minor change to use the term `link` instead of `button`. This is because the behaviour of email clients is not uniform and the link may be presented as  a button or a link or something else entirely.

2024-05-23 10:49 UTC, BlessedDev commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +  <h2 class="heading-medium">Add a one-click unsubscribe button to the email header</h2>
Technically it could be presented as a button or a link depending on the email client, so it should be along the lines of `Add a one-click unsubscribe link to appear in the email header` in order to reduce confusion.

2024-05-23 10:49 UTC, BlessedDev commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +  <p class="govuk-body">To add a one-click unsubscribe button, follow the instructions in our <a class="govuk-link govuk-link--no-visited-state"
I would suggest replacing `button` with `link`

2024-05-23 10:49 UTC, BlessedDev commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +    <li>Add a one-click unsubscribe button to the email header.</li>
Technically it could be presented as a button or a link depending on the email client, so it should be along the lines of `Add a one-click unsubscribe link to appear in the email header` in order to reduce confusion.

2024-05-23 11:03 UTC, saimaghafoor commented on app/templates/views/guidance/using-notify/unsubscribe-links.html
> +  <h2 class="heading-medium">Add a one-click unsubscribe button to the email header</h2>
Thanks Gozie. This is interesting. If it'll appear as either a button or link then perhaps we can refer to it as just 'one-click unsubscribe' that appears in the email header. 

I've checked Google and they refer to it as one-click unsubscribe

2024-05-23 11:17 UTC, saimaghafoor commented
Tweaked content to remove references to a button. Used 'one-click unsubscribe' (which Google also use)

2024-05-23 11:23 UTC, BlessedDev approved these changes

2024-05-23 11:31 UTC, merged