Download unsubscribe request reports
alphagov/notifications-admin pull request #5157
Opened 2024-07-30 18:19 UTC by BlessedDev

This PR enables downloading an `unsubscribe-request-report` as described in [this](https://trello.com/c/BeZGTW0E/53-let-users-download-email-unsubscribe-requests) card.
The PR for the API endpoints can be found [here](https://github.com/alphagov/notifications-api/pull/4152).

2024-07-31 11:06 UTC, quis requested changes

2024-07-31 11:06 UTC, quis commented on app/main/views/unsubscribe_requests.py
> +                    f"to {format_date_normal(report['latest_timestamp'])}.csv",
Filenames should have numeric dates so they are listed in order once downloaded
```suggestion
                    f"{format_date_numeric(report['earliest_timestamp'])} "
                    f"to {format_date_numeric(report['latest_timestamp'])}.csv",
```

2024-07-31 11:06 UTC, quis commented on app/main/views/unsubscribe_requests.py
> +                "original_file_name": "Contact list file name",
```suggestion
                "original_file_name": "Uploaded spreadsheet file name",
```

2024-07-31 11:06 UTC, quis commented on app/main/views/unsubscribe_requests.py
> +        raise e
Same point about `try/except` here

2024-08-01 08:58 UTC, BlessedDev commented on app/main/views/unsubscribe_requests.py
> +            raise e
I had intended to capture specific `http 400` errors raised by the API  but changed my mind and forgot to adjust the code.

2024-08-05 13:26 UTC, quis approved these changes
Good to go once the API side is merged

2024-08-06 08:31 UTC, merged