Collapsible checkboxes update
alphagov/notifications-admin pull request #5183
Opened 2024-08-19 13:58 UTC by kr8n3r

## What

## Why

## Changes

**No change to built static JS files with updated babel-core**
<img width="1060" alt="Screenshot 2024-08-19 at 12 11 34" src="https://github.com/user-attachments/assets/c1cd58d4-b2ee-484e-b5dd-403e9b027952">

2024-08-27 10:12 UTC, kr8n3r commented
@quis when you're back to speed after your holiday, if you have any thoughts on this, please feel free to comment

2024-08-27 10:43 UTC, quis commented
I’m ok with this, if we can use the same arrow style as the details component:
> [ ▶ Collapsed ]
>
> [ ▼ Expanded ]
> ☑️ 
> ☑️ 

But then I wonder if we shouldn’t just be using the details component anyway. Thoughts?

2024-08-28 11:13 UTC, kr8n3r commented
quick prototype using `details`
https://github.com/alphagov/notifications-admin/compare/collapsible-checkboxes-with-details?expand=1

![Screenshot 2024-08-28 at 12 10 37](https://github.com/user-attachments/assets/39e29fc1-d18f-4ba2-af86-d8cc1136371f)
![Screenshot 2024-08-28 at 12 10 47](https://github.com/user-attachments/assets/6455ceba-efa4-4738-badb-6901d2369f3a)
![Screenshot 2024-08-28 at 12 10 42](https://github.com/user-attachments/assets/57a360e5-f214-4677-ac2f-e2f411523261)

2024-08-28 15:47 UTC, tombye requested changes
Spotted a few things, all commented, but this is some nice work overall and thanks for doing all the wrangling with jest and babel.

If we leave it as a button, not a `<details>`, I think we should make the arrow the same as the day/time picker:

<img width="371" alt="image" src="https://github.com/user-attachments/assets/49f29083-9772-4ea9-9f95-e24e975c0e7b">

## Things from cross browser testing

The button seems to start with spacing above and then move on the first click on Safari on MacOS and iOS. This is on MacOS:

![moving_button_macos](https://github.com/user-attachments/assets/0d108c34-f798-465f-9242-ed1cc40a0b86)

I noticed the folder icon for the summary still appearing on IE11. Not a game changer but didn't think this was intentional:

<img width="407" alt="image" src="https://github.com/user-attachments/assets/18438a35-570c-4803-acce-73eda9fc1f85">

## Suggestion for changing the order of the HTML

The other thing I'd suggest changing is to move the button out of the fieldset. It's currently a bit strange to hear the button after the legend:
- "[Group] Folders this team member can see"
- "Choose folders [button, expanded]"
- "[Unordered list]" (of checkboxes)

Moved outside, it's more like:
- "Choose folders [button, expanded]"
- "[Group] Folders this team member can see"
- "[Unordered list]" (of checkboxes)

...which I think makes more sense as the button label sets the expectation of folders and the group label following it meets that expectation.

2024-08-28 15:47 UTC, tombye commented on package.json
> +    "@babel/core": "^7.25.2",
Can we lock this down to an exact version number please, to match the others? Same with all others added in the same way.

2024-08-28 15:47 UTC, tombye commented on tests/javascripts/collapsibleCheckboxes.test.mjs
>  afterAll(() => {
Doesn't look like we need this `afterAll` now.

2024-08-29 14:28 UTC, kr8n3r commented
> Spotted a few things, all commented, but this is some nice work overall and thanks for doing all the wrangling with jest and babel.
> 
> If we leave it as a button, not a `<details>`, I think we should make the arrow the same as the day/time picker:
> 
> <img alt="image" width="371" src="https://private-user-images.githubusercontent.com/87140/362349856-49f29083-9772-4ea9-9f95-e24e975c0e7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjg3MzIsIm5iZiI6MTcyNDkyODQzMiwicGF0aCI6Ii84NzE0MC8zNjIzNDk4NTYtNDlmMjkwODMtOTc3Mi00ZWE5LTlmOTUtZTI0ZTk3NWMwZTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNGUwMjgyMGY1MWNiNDYzODc3NWY2NmVlMDE2YjAwZmI4ZDEyODFmZGZlNmU5YzM1M2FiYzNiN2I2ZmUxY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AYbLN1_OOLUnNuUXRl2IErV8vx-wNlH60iQQvH6LQ_c">
> ## Things from cross browser testing
> The button seems to start with spacing above and then move on the first click on Safari on MacOS and iOS. This is on MacOS:
> 
> ![moving_button_macos](https://private-user-images.githubusercontent.com/87140/362359575-0d108c34-f798-465f-9242-ed1cc40a0b86.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjg3MzIsIm5iZiI6MTcyNDkyODQzMiwicGF0aCI6Ii84NzE0MC8zNjIzNTk1NzUtMGQxMDhjMzQtZjc5OC00NjVmLTkyNDItZWQxY2M0MGEwYjg2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMmU4N2RiNTc1MzJmNjFmMTY4ZmU2ZTQyNTI1YjU3MzlmZGY2ZTlkNWVlMmQ5N2Q4OTE0NjZjNmYwMTBmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I6YI532crv2geZ_h9w1zDZmanlfeOby8b7AGFspN5pQ) [ ![moving_button_macos](https://private-user-images.githubusercontent.com/87140/362359575-0d108c34-f798-465f-9242-ed1cc40a0b86.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjg3MzIsIm5iZiI6MTcyNDkyODQzMiwicGF0aCI6Ii84NzE0MC8zNjIzNTk1NzUtMGQxMDhjMzQtZjc5OC00NjVmLTkyNDItZWQxY2M0MGEwYjg2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMmU4N2RiNTc1MzJmNjFmMTY4ZmU2ZTQyNTI1YjU3MzlmZGY2ZTlkNWVlMmQ5N2Q4OTE0NjZjNmYwMTBmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I6YI532crv2geZ_h9w1zDZmanlfeOby8b7AGFspN5pQ) ](https://private-user-images.githubusercontent.com/87140/362359575-0d108c34-f798-465f-9242-ed1cc40a0b86.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjg3MzIsIm5iZiI6MTcyNDkyODQzMiwicGF0aCI6Ii84NzE0MC8zNjIzNTk1NzUtMGQxMDhjMzQtZjc5OC00NjVmLTkyNDItZWQxY2M0MGEwYjg2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMmU4N2RiNTc1MzJmNjFmMTY4ZmU2ZTQyNTI1YjU3MzlmZGY2ZTlkNWVlMmQ5N2Q4OTE0NjZjNmYwMTBmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I6YI532crv2geZ_h9w1zDZmanlfeOby8b7AGFspN5pQ) [ ](https://private-user-images.githubusercontent.com/87140/362359575-0d108c34-f798-465f-9242-ed1cc40a0b86.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjg3MzIsIm5iZiI6MTcyNDkyODQzMiwicGF0aCI6Ii84NzE0MC8zNjIzNTk1NzUtMGQxMDhjMzQtZjc5OC00NjVmLTkyNDItZWQxY2M0MGEwYjg2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkMmU4N2RiNTc1MzJmNjFmMTY4ZmU2ZTQyNTI1YjU3MzlmZGY2ZTlkNWVlMmQ5N2Q4OTE0NjZjNmYwMTBmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I6YI532crv2geZ_h9w1zDZmanlfeOby8b7AGFspN5pQ)
> 
> I noticed the folder icon for the summary still appearing on IE11. Not a game changer but didn't think this was intentional:
> 
> <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/87140/362356765-18438a35-570c-4803-acce-73eda9fc1f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjg3MzIsIm5iZiI6MTcyNDkyODQzMiwicGF0aCI6Ii84NzE0MC8zNjIzNTY3NjUtMTg0MzhhMzUtNTcwYy00ODAzLWFjY2UtNzNlZGE5ZmMxZjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMTZmOGUzODM5MDMyZjhjODI2YTBlYzM3YzFlZmJlZDI5NWRhY2M4MGQzMjcyMTFhOTFjODEwOWE2Yjk0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U7x2fMInE7jSzv7b60K7npi6eNAXROjC7a1rvZ61688">
> ## Suggestion for changing the order of the HTML
> The other thing I'd suggest changing is to move the button out of the fieldset. It's currently a bit strange to hear the button after the legend:
> 
> * "[Group] Folders this team member can see"
> * "Choose folders [button, expanded]"
> * "[Unordered list]" (of checkboxes)
> 
> Moved outside, it's more like:
> 
> * "Choose folders [button, expanded]"
> * "[Group] Folders this team member can see"
> * "[Unordered list]" (of checkboxes)
> 
> ...which I think makes more sense as the button label sets the expectation of folders and the group label following it meets that expectation.

- updated arrow design
- not showing folder icon in non-supported browsers
- fixed Safari spacing
- moved the button before the fieldset

2024-09-03 10:10 UTC, tombye approved these changes
All issues fixed and it now makes much more sense when used with a screen reader due to the changes to the order of the elements. Nice work, ready to go now 👍🏻

2024-09-03 10:14 UTC, merged