Update guidance-links-urls-emails.html
alphagov/notifications-admin pull request #5201
Opened 2024-09-10 12:55 UTC by saimaghafoor

Adding unsubscribe link instructions to guidance (removing section on unsub links as a separate instruction)

This should be merged/deployed at the same time as the PR to remove unusb content https://github.com/alphagov/notifications-admin/pull/5202

2024-09-11 09:32 UTC, karlchillmaid commented on app/templates/partials/templates/guidance-links-urls-emails.html
> +    href="https://www.notifications.service.gov.uk/using-notify/api-documentation">API documentation</a>. This is an API only feature.</p>
Is this the instruction for API users? If so, we should open with that, to distinguish it from the ‘check the box’ instruction above.

2024-09-16 09:27 UTC, quis requested changes

2024-09-16 09:27 UTC, quis commented on app/templates/partials/templates/guidance-links-urls-emails.html
> +<p class="govuk-body">Find out why you need to add <a class="govuk-link govuk-link--no-visited-state" href="Unsubscribe links – GOV.UK Notify">unsubscribe links</a>.</p>
```suggestion
<p class="govuk-body">Find out why you need to add <a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('main.guidance_unsubscribe_links') }}">unsubscribe links</a>.</p>
```

2024-09-16 09:27 UTC, quis commented on app/templates/partials/templates/guidance-links-urls-emails.html
> +<p class="govuk-body">Select the 'Add an unsubscribe link' checkbox to let recipients request to opt out. </p>
```suggestion
<p class="govuk-body">Select the ‘Add an unsubscribe link’ checkbox to let recipients request to opt out. </p>
```

2024-09-17 10:46 UTC, quis approved these changes
Good to merge once the feature is launched

2024-09-27 13:53 UTC, karlchillmaid commented on app/templates/partials/templates/guidance-links-urls-emails.html
> +<p class="govuk-body">Find out why you need to add <a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('main.guidance_unsubscribe_links') }}">unsubscribe links</a>.</p>
Should we be adding this to the Links and URLs page when we already have a page called ‘Unsubscribe links’?

2024-10-14 11:26 UTC, merged