Replace Gulp with Rollup
alphagov/notifications-admin pull request #5239
Opened 2024-10-04 13:20 UTC by kr8n3r

2024-10-11 09:51 UTC, tombye requested changes
I added a few comments but all minor and this is great work.

I really appreciate the detail in each commit too, helps reviewing.

For reviewing I:
- compared file sizes between the old and new bundles (smaller!)
- checked all JS is present in the new bundle and running
- tried with PROD and DEV versions and observed the sourcemaps being added or not correctly

Initially I thought the approach, of using RollupJS for everything, was a bit bonkers but after getting used to it I like having it all in once place to look at. I have a slight fear about the plugins becoming unmaintained (which I think you mention in the description) but the fact that those not in the rollup-plugins repo are either wrappers for stuff we could run as shell commands (Sass and Post-CSS) or, perhaps just NodeJS scripts (URL replacement) makes this less of a worry.

Should be good to go once the comments are addressed 👍🏻

2024-10-11 09:51 UTC, tombye commented on app/assets/stylesheets/components/pill.scss
> -    text-align: left;
Was this change a result of the new linting rules?

2024-10-11 11:20 UTC, kr8n3r commented on app/assets/stylesheets/components/pill.scss
> -    text-align: left;
sorry no, property was [duplicated](https://github.com/alphagov/notifications-admin/blob/5fcdb6f6c3976bfed7c2c3e833ea2235a5032e4a/app/assets/stylesheets/components/pill.scss#L125) so instead of changing a rule, i removed it. didn't think it warranted a separate commit. will add it to the commit description though

2024-10-11 14:07 UTC, kr8n3r commented on rollup.config.mjs
> +const isProduction = process.env.NODE_ENV === 'production';
if the variable is not defined we want production behaviour?

2024-10-17 09:27 UTC, tombye commented on rollup.config.mjs
> +const isProduction = process.env.NODE_ENV === 'production';
Yeah, as a protection against accidently shipping dev code. That was the old behaviour, I think.

2024-10-17 09:54 UTC, kr8n3r commented on rollup.config.mjs
> +      sourcemap: isProduction ? false : 'inline'
https://github.com/alphagov/notifications-admin/pull/5239/commits/b989120775213e125a7b4dc9ef2daf3e55429dd0 should address this

2024-10-17 09:54 UTC, kr8n3r commented on rollup.config.mjs
> +const isProduction = process.env.NODE_ENV === 'production';
https://github.com/alphagov/notifications-admin/pull/5239/commits/b989120775213e125a7b4dc9ef2daf3e55429dd0 should address this

2024-10-17 14:49 UTC, kr8n3r commented on package.json
> +    "@eslint/js": "^9.11.1",
done

2024-10-17 14:49 UTC, kr8n3r commented on app/assets/stylesheets/components/pill.scss
> -    text-align: left;
done

2024-10-23 09:24 UTC, tombye approved these changes
Thanks for sorting all the things I commented on. Now looks good 👍🏻

2024-10-28 17:28 UTC, kr8n3r commented
sorry @tombye I rebased...

2024-10-31 10:23 UTC, tombye approved these changes
No changes other than a rebase so 👍🏻

2024-10-31 12:11 UTC, merged