Approver service join request approver page
alphagov/notifications-admin pull request #5246
Opened 2024-10-10 15:31 UTC by spatel033

When approver gets service-join-request, they would approver page or request status page. More details on [this card](https://trello.com/c/pQovKftH/976-create-new-approver-flow-for-request-to-join-a-service).

Request approve page:
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/2cfae454-4078-4c14-a94f-31733be64a05">

Request approved page:
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/63b3a255-64af-4d1f-8295-ce290ac3e723">

Request refused page:
<img width="1243" alt="image" src="https://github.com/user-attachments/assets/199de990-c45d-4e4a-a75e-48463661ad8a">

2024-10-10 15:44 UTC, quis commented on app/templates/views/service-join-request-rejected.html
> +    {{ rejected_by.name }} already refused their request on {{ rejected_at.strftime('%-d %B') }}.
Use a formatter rather than hard-code string formatting:
```suggestion
    {{ rejected_by.name }} already refused their request on {{ rejected_at|format_date_short }}.
```

Comes from:
https://github.com/alphagov/notifications-admin/blob/a5be2df07d3b97dc981855fd5d048b56456a7c3b/app/formatters.py#L97-L98

This is:
- easier to read
- handles timezones properly

2024-10-10 15:44 UTC, quis commented on app/models/service.py
> +class ServiceJoinRequest(JSONModel):
Nice work making a model class here

2024-10-11 07:08 UTC, kr8n3r commented
what's the flow to test this and mural access is blocked so can't see designs

2024-10-11 08:52 UTC, karlchillmaid commented
The content needs to be updated to match the wording in [the content design document](https://docs.google.com/document/d/15jG6UW7aoCQ15E8uTVfpMG_lEYtCbJueEg-ww2O-6Nc/edit?usp=sharing) (linked from the Mural)

2024-10-14 12:24 UTC, karlchillmaid commented on app/templates/views/join-service-request-approver.html
> +      {{ "Do you want to let {} join '{}'?".format(requester.name, requested_service.name)}}
Change to ‘smart’ (curly) quotes.

```suggestion
      {{ "Do you want to let {} join ‘{}’?".format(requester.name, requested_service.name)}}
```

2024-10-14 12:25 UTC, karlchillmaid commented on app/templates/views/service-join-request-user-already-joined.html
> +    {{ user_to_invite.name }} is already member of '{{ current_service.name }}'.
Use smart/curly quotes

```suggestion
    {{ user_to_invite.name }} is already member of ‘{{ current_service.name }}’.
```

2024-10-14 12:28 UTC, karlchillmaid approved these changes
Apart from the Smart/Curly quote suggestions I made – the content looks like it matches the work in the content document :-)

2024-10-17 09:24 UTC, kr8n3r approved these changes

2024-10-21 13:26 UTC, whpearson requested changes

2024-10-21 13:26 UTC, whpearson commented on tests/app/main/views/test_manage_users.py
> +        "service_join_request_id": requester_id,
This is a bit confusing. I don't think it should be requester_id but request_id or service_join_request_id. Or am I confused.

2024-10-21 13:26 UTC, whpearson commented on tests/app/main/views/test_manage_users.py
> +    def _get(requester_id):
Same here, should it be request_id?  And in the other service_join_request mocks?

2024-10-21 15:02 UTC, spatel033 commented on tests/app/main/views/test_manage_users.py
> +        "service_join_request_id": requester_id,
Nice catch!

2024-10-21 15:05 UTC, whpearson approved these changes

2024-10-22 10:07 UTC, whpearson approved these changes

2024-10-22 11:01 UTC, merged