Fix truncated text on pages
alphagov/notifications-admin pull request #5270
Opened 2024-10-28 07:29 UTC by kr8n3r

2024-10-30 16:01 UTC, tombye requested changes
Good, clear, work that touches a lot of our codebase to nice one for finding all the bits of each type of truncation.

I've left a few comments but, overall, I'm interested to know if we should just be swapping out our current clipping of text with an ellipsis for the gradual breaking behaviour you get from `word-break: break-word` (see `overflow-wrap: break-word` section on https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap for that, which is the same).

2024-10-31 11:10 UTC, kr8n3r commented on app/assets/stylesheets/views/dashboard.scss
> +.file-list .js-child-has-focus {
👍 done

2024-10-31 11:15 UTC, kr8n3r commented on app/assets/stylesheets/components/table.scss
> -      .hint,
added

2024-10-31 11:17 UTC, kr8n3r commented on app/assets/stylesheets/views/dashboard.scss
> -    white-space: nowrap;
👍 done

2024-10-31 14:14 UTC, tombye commented on app/assets/stylesheets/views/dashboard.scss
> -  &.file-list-filename,
We've been discussing this outside of this pull request and Jani's since been trialing this approach so marking this as resolved.

2024-11-08 12:03 UTC, kr8n3r commented
closing for now in favour of https://github.com/alphagov/notifications-admin/pull/5288 which has a smaller scope.
will keep the branch for as while

2024-11-08 12:03 UTC, closed without merging