Conditionally focus template page forms
alphagov/notifications-admin pull request #5291
Opened 2024-11-08 19:25 UTC by kr8n3r

Fixes: https://trello.com/c/Dg0mE6e5/1041-validation-for-new-template-form-doesnt-focus-the-error-summary

When a user clicks say "add a new template" button, we show and focus that form. Should then a user submit that form without any selection, we reload the page, show the error-summary banner, check which form they submitted and then show it and focus it.

This causes issues for screen render users, which expected the error summary to be focused.

This PR amends the javascript module logic to check if the rendered page contains an error summary. If it does, we don't focus the form and let Design System Javascript handle error-summary.

As the error-summary contains the link to the errored form, users can then make changes quickly.

2024-11-12 12:22 UTC, tombye requested changes
The code makes sense and it works well. The spacing on smaller screens / is a bit tight between the error summary and the side nav:

<img width="317" alt="image" src="https://github.com/user-attachments/assets/5176e6f8-469e-415b-ab5d-820d59a4ba59">

I think it would be worth seeing if we can fix that but everything else looks good.

2024-11-12 14:23 UTC, kr8n3r commented
@tombye in most other pages there's a back-link between the left-nav and error summary. adding bottom spacing to the left nav will affect all the other pages, so should we address that in this PR?

2024-11-12 15:50 UTC, tombye commented
I was thinking that might make it a good candidate for just using an override class from design system on the top of the error summary. That way it's just for that page.

2024-11-12 15:59 UTC, kr8n3r commented
can we actually pass in a class to the error-summary the way we have it set up as it's automagical?

2024-11-13 12:30 UTC, kr8n3r commented
what do you think? https://github.com/alphagov/notifications-admin/pull/5291/commits/f3a1e5754e0f81689980064b471fd804140e4ca6

<img width="972" alt="Screenshot 2024-11-13 at 12 28 53" src="https://github.com/user-attachments/assets/0e998808-a519-4b2f-9f36-8c84fcba337b">

2024-11-14 10:18 UTC, tombye approved these changes
Thanks for addressing the comment. Now looking good to go 👍🏻

2024-11-15 09:12 UTC, merged