Add csp_nonce for inline script and gov_template
alphagov/notifications-admin pull request #5325
Opened 2024-12-11 17:17 UTC by spatel033

2024-12-13 11:35 UTC, kr8n3r commented
missed https://github.com/alphagov/notifications-admin/blob/96d1eb0ae2dff75a8260282fe062c63a420912bb/app/templates/components/webauthn-api-check.html#L2

2024-12-13 11:55 UTC, tombye requested changes
I left a comment but also wanted to suggest this adds a test to [this block in `tests/conftest.py`](https://github.com/alphagov/notifications-admin/blob/96d1eb0ae2dff75a8260282fe062c63a420912bb/tests/conftest.py#L2987) for script tags that either contain inline code or reference a file not hosted on our domain. That would both identify any current scripts without the `nonce` attribute and protect us from adding any in future.

2024-12-13 11:55 UTC, tombye commented on app/templates/admin_template.html
> +  <script nonce="{{ request.csp_nonce }}" type="module" src="{{ asset_url('javascripts/all-esm.mjs') }}"></script>
From my understanding of the use of the `nonce` attribute, we only need to apply it to scripts that are either from external domains or those that contain inline code. These tags reference scripts from our own domain and contain no inline code so shouldn't need it.

2024-12-13 15:12 UTC, tombye requested changes
Sorry to be asking for changes again, I'm not sure my last review was clear enough, but I think these changes would mean we could spot and guard against all unsafe script tags.

2024-12-13 15:12 UTC, tombye commented on tests/conftest.py
> +
This is great but I think it just checks a specific js file we load and doesn't check inline scripts. I'm guessing at the code but maybe this method could do with a few changes to check script tags for external js files and inline scripts. I don't write much python so the code could be wrong but I was thinking something like:

```python
@staticmethod
def test_for_csp_nonce(page):
    for script_tag in page.select("script"):
        src = script_tag.get("src")
        nonce = script_tag.get("nonce")        
        if src and script_tag.text: # inline script tag
            assert nonce is not None
        if not src.startswith('https://static.example.com'): # script tag for file from external domain
            assert nonce is not None
```

2024-12-13 15:12 UTC, tombye commented on tests/conftest.py
> +            ClientRequest.test_for_script_csp_nonce(page)
I think this needs a condition testing a boolean with the same name, like the others above it, and for that to be added as a parameter to the following method definitions, so the test can be turned on or off:
- https://github.com/alphagov/notifications-admin/blob/bbeb4fbfc1e6e75d62b1214df5d48192fb94a50c/tests/conftest.py#L2936
- https://github.com/alphagov/notifications-admin/blob/bbeb4fbfc1e6e75d62b1214df5d48192fb94a50c/tests/conftest.py#L2948
- https://github.com/alphagov/notifications-admin/blob/bbeb4fbfc1e6e75d62b1214df5d48192fb94a50c/tests/conftest.py#L2960

Sorry if I didn't mention that in my previous review, I'm less familiar with this code.

2024-12-13 16:02 UTC, spatel033 commented on tests/conftest.py
> +
Test does not expect `nonce` for `src="{{ asset_url('javascripts/all.js') }}` , for example
`<script src="https://static.example.com/javascripts/all-esm.mjs?42034a5684d7ffec20704fe4ba8b9543" type="module"></script>`

But it expect `nonce` for all other javascript files, for examples
`<script nonce="TESTs5Vr8v3jgRYLoQuVwA">document.body.className += ' js-enabled' + ('noModule' in HTMLScriptElement.prototype ? ' govuk-frontend-supported' : '');</script>`
`<script src="https://static.example.com/javascripts/all.js?56abf841397f87250b4de8efb35b0826" type="text/javascript"></script>`


The test covers both cases [with `src`](https://github.com/alphagov/notifications-admin/pull/5325/files#diff-96cbd07e702e8ccd28e9d25faef4d3bcff2a45127f89f30c71c71f8820bff060R139) and without `src` (as mentioned above)

2024-12-16 09:51 UTC, kr8n3r commented on tests/conftest.py
> +
I removed 'nonce` from inline `<script>` tag on app/templates/components/webauthn-api-check.html and got a failed `test_should_show_security_keys_page` on

```
    @staticmethod
    def test_for_script_csp_nonce(page):
        for script_tag in page.select("script"):
            src = script_tag.get("src")
            nonce = script_tag.get("nonce")
            if src and "javascripts/all-esm.mjs" in src:
                assert nonce is None
            else:
>               assert nonce == fake_nonce
E               AssertionError: assert None == 'TESTs5Vr8v3jgRYLoQuVwA'

tests/conftest.py:3164: AssertionError
```

so I gather test is working

2024-12-16 09:53 UTC, kr8n3r approved these changes
based on https://github.com/alphagov/notifications-admin/pull/5325#discussion_r1886507980 I'm happy with this but it should wait for Tom as he requested changes

2024-12-17 09:57 UTC, tombye commented on tests/conftest.py
> +
I might be wrong but I thought this line:
```python
if src and "javascripts/all-esm.mjs" in src:
```
...would catch this script tag:
```html
<script type="module" src="{{ asset_url('javascripts/all-esm.mjs') }}"></script>
```
...but not this script tag:
```html
<script  type="text/javascript" src="{{ asset_url('javascripts/all.js') }}"></script>
```
That also seems to reflect the code in `app/templates/admin_template.html` because the script tag for 'javascripts/all.js' has a nonce but, I think, shouldn't need one because it is served from the same static assets domain and is a file, not an inline script.

2024-12-17 11:02 UTC, spatel033 commented on tests/conftest.py
> +
Thank you for your suggestions. Refactored `app/templates/admin_template.html` and test cases.

2024-12-17 21:11 UTC, tombye approved these changes
Thanks for going through all the changes requested. Looks great now 👍🏻

2024-12-18 13:42 UTC, kr8n3r approved these changes

2024-12-19 13:41 UTC, merged